<!doctype html public "-//w3c//dtd html 3.2//en">

<html>

<head>
<title>Dimension Cualitativa - Introducción</title>
<link rel="stylesheet" type="text/css" href="estilo.css">
<SCRIPT language="JavaScript1.2" src="../../js/main15.js" type="text/javascript""></SCRIPT>
</head>
</head>

<body>
<DIV id="TIP" style="visibility:hidden;position:absolute;z-index:1000;top:-100;"></DIV>
<SCRIPT language="JavaScript1.2" type="text/javascript" src="filosofia.js" ></SCRIPT>

<div class="subtit" style="position:absolute;top:2px;">
La Dimensión Cualitativa
</div><br><br>

<div id="cuerpo" style="width:570px;">

<h2>PARTE II: FILOSOFIA INTEGRALISTA</h2>

<p><I>Este documento pretende ser una solicitud,  dirigida a su conciencia como parte integral de una familia,  una comunidad, un país, y  a la conciencia de una humanidad que, por su actitud de violencia e inconsciencia, nos  pareciera que desea desaparecer.</I>

<P>Considero, que tal y como Ud. ha leído en los párrafos anteriores, su contenido,  como un objetivo muy especial, nos permite hablar de  la posibilidad de que hayamos estado todos, o por lo menos una gran parte, completamente equivocados.  Los criterios y pensamientos filosóficos, sociales, científicos, económicos y políticos han cambiado, y se han  transmutado en diversas formas en toda la sociedad del planeta.

<p>Expreso  prudentemente, y con profundo respeto, a todos cuantos disientan  de  nuestro <i>estar circunstancial</i>, que se encuentra en todo caso,  por debajo de nuestro <i>ser esencial</i>,  que es ahora y solamente ahora, cuando se puede asegurar que del planteamiento de la investigación extensiva, con  su respectiva filosofía de la realidad,  han  surgido  dos  testigos de excepción, uno natural y el otro de reflexión persistente sobre <i>como</i> ellos ya  nos habían  hablado y preavisado,  pero no se sabe por cuál razón no se quería  o no se podían escuchar. Había, y aún perdura, demasiado ruido, lo cual los hace poco audibles:  uno de ellos es la naturaleza y el otro la intuición consciente y sistemática, además de metodológica de: <b>¿Cómo podríamos sobrevivir a la violencia y descomposición ya generalizadas?</b>

<p>No se quiere, y además no se debe  ni se  puede, por ninguna razón, llegar a esa calamitosa situación de agonía colectiva que nos espera si no somos capaces de reaccionar. Debemos entonces dejar plasmada suficientemente la nueva verdad en movimiento, los verdaderos conceptos de espacio y tiempo, la verdadera geo-historia de la energía y la información; la nueva ciencia, sus  hechos, sus procesos y sus ocultos <i>sistemas reales</i>, que siempre estuvimos ignorando o eludiendo. Debemos también reflexionar sobre tal realidad en el cambio que le es inherente.

<p>Pasemos  al nivel, sitio y país donde nos encontramos. A pesar de la inconsciencia continua de los transgresores y poseedores de toda clase de poderes interactivos, diseminados   por todas partes del  mundo, hemos logrado subsistir.  Pero también, en esta misma investigación de carácter extensivo y eminentemente social, se  pudo llegar a los oscuros y terribles rincones del hambre y la ignorancia interactivos, en los que se logró el mantenimiento de la  observación sobre convivencia, subsistencia y supervivencia.  A este nivel de la nueva  explicación, se recibieron, como era de esperar,  numerosos, impertinentes e  injustos maltratos,  distribuyéndose, en cambio, un copioso patrimonio de verdad social  y aliento de justicia, mezclado con un increíble respeto y cariñosa inducción para todos los seres que nos rodearon durante cuarenta y cuatro años. Se puede asegurar que es en esos episodios de  contradicción donde apareció el valor indiscutible del abecedario con sus fuentes histórico-culturales y el desprendimiento semiótico, como puede verse en una sola letra de las 28, cada cual tiene su significado y sentido; vemos las  doce (12)  <b>“P”</b>, abriendo el ¿Porqué? en dirección al ¿Para qué? , de la Pertinencia, la Persistencia y la Pertenencia, la Prudencia, la  Paciencia, para lograr nuevas  Perspectivas, Proyectivas y Prospectivas, el llamdo Posicionamiento, la Planificación y la Programática. Todos ellos son cualidades activas de una sistemática significativa. Durante mucho tiempo todo simulaba ser, aparentemente  para nada (ningún fin trascendente y al mismo tiempo práctico). ¿Cómo podía  entenderse,  entonces, que con sólo ser y estar vinculados allí, en esas áreas que simulaban no tener respuestas, se estaba gestando una  producción en la más trascendente dimensión humana de carácter prospectivo? Y aprendimos a encontrar y  <i>abrir</i>  la verdadera visión de la realidad universal.Solo comenzando surgieron los contactos y vínculos, con la aritmética razonada, la gramática generativa y la lógica: de todas ellas fueron  sus contenidos los que transfirieron los conceptos en la geo historia de la cultura y la tecnología.

<p>¿Porqué y cómo fue que se logró encontrar y poner a nuestro servicio la verdadera realidad con sus inmensos recursos? ¿Qué tiene que ver saber <i>leer</i> la realidad, con la felicidad personal? Desde  esa <i>casi desconocida relación</i>, pero haciendo muchas relaciones sistematizadas y coherentes, y manteniendo la misión, se obtuvo el gran premio del logro final: <i>“Comprender el TODO  y el COMO  complejos”</i>. Pero digamos  algo más: Toda  la  vida, en la familia, los negocios, la profesión, las  querencias y el propio ser, podrán  satisfacerse, estremeciéndose de  felicidad,   al haber encontrado  la manera de abrir y utilizar la realidad.   Podrán  admirarse de cuán pequeños  <i>somos</i> cuando no entendemos lo que  <i>no somos</i>,  sino que simplemente, estamos, definitivamente, en nuestro propio ser, y es en esa entidad de relaciones usualmente, donde residen el éxito y el bienestar.

<p>Es por eso, por lo que ya somos,  que podemos llegar a  ser <i>mucho más</i>  y  también podemos llegar a <i>poseer lo  que siempre nos negamos a tener</i>. Eso es lo que siempre se puede entregar sin perderlo: <i>La felicidad de ser</i> que está radicalmente unida a nuestro potencial de ser cada vez más que nosotros mismos en dos sentidos: 1) aprender a dar conocimientos,  con lo que nunca dejamos de tenerlos, y al transferirlos hacemos crecer a los demás; 2) Todo lo que damos, además de no perderse,  acrecienta nuestro patrimonio, que crece con el ciclo de recibir, acrecentado, todo lo que dimos. 

<p>"El que sepa <i>abrirse a la realidad podrá sentirse y ser feliz</i>". El que no lo sepa, trate de aprenderlo. Solamente los seres inteligentes podrán conocerla, constituir familias, comunidades, municipios, naciones y una humanidad consciente de su realidad, y por lo tanto, con capacidad de ser feliz.

<p>A través del texto usted podrá comprender, entonces, qué son los sistemas inteligentes, cómo son y están en contacto con la realidad y la felicidad. ¿Cómo podemos integrar espacio y tiempo, la energía que nos acompaña,  la información que tenemos, y que además nos  sigue alimentando continuamente, si no  entendemos  y nos integramos plenamente como causas y efectos de todo acontecer y del nuestro propio?

<p>No nos podemos explicar  que  si la realidad y la felicidad del ser humano fueron las fuentes de la existencia misma, y si en el universo reina una gran armonía física, conceptual y social   ¿por qué razón vinimos a dar a un mundo de violencia y descomposición? Cabe hacerse una pregunta: Aparte de que nosotros somos los responsables y por lo tanto imputables ¿quiénes fueron  o quiénes somos los culpables de esta situación?

<p>Realmente, cuando iniciamos las investigaciones extensivas y determinamos que la estrategia de tal investigación era conceptualizar  vivencialmente los usos, las situaciones y problemas sociales, y que de esas resultas nacía  la utilización de los nuevos conceptos, entendimos que eso significaba  <b>UN CICLO</b>. Fue allí donde se dio el primer paso hacia la Filosofía  Integralista. Observamos que de alguna manera se había fracturado una forma de pensar que divorciaba la teoría conceptual de la práctica social, la filosofía de la ciencia fáctica, la gramática de la aritmética. En realidad el gran descubrimiento fue que el conocimiento y la acción eran y producían ciclos y frecuencias de una misma realidad. 

<p>El Kosmos (con K) es uno solo. En él, el ser humano es apenas una reciente entidad en el espacio y el tiempo; la época cuaternaria y la antropología son apenas unas incipientes figuras de la ciencia universal. Lógicamente, en pocos años, apenas cinco mil, se han acumulado transferencias de conocimientos que en otra época hubieran necesitado veinte millones de años.  

<p>Pero no debemos olvidar que la cronología del planeta y de la humanidad acumulan una gran discrepancia que nos hace asimilarnos a  una base logarítmica de compresión de <i>tiempo cronológico</i> en la comparación de ambas entidades.  Además, son  inversamente proporcionales a la longitud del tiempo transcurrido, con pequeñísimas proporciones de fluidos en los flujos de energía e información con los que se desarrollan actualmente en pocos años. Esto se acelera  año tras año.  En  un período de millones de años de evolución, sobresale la  portentosa capacidad  del ser humano como relacionador inteligente de la realidad del cambio acelerado.. Esa evolución no ha sido una especificidad fisiológica o biológica, sino que en ella han concurrido y se han adecuado  elementos existenciales con características importantes: 1) Elementos bio-ecológicos; 2) psico-sociológicos y 3) axiológico-espirituales. 

<p>La ciencia, la filosofía y la religión han interactuado con los elementos factores del ser, el poder y el poseer. La falta de una concepción hologenética no había permitido conceptuar ni valorar la relación, el cambio ni su tercera relación de cambio en las relaciones y relaciones de cambio, todo ello en el espacio-tiempo y causa-efecto. 

<p><b>Estamos asistiendo, en este comienzo del tercer milenio, a una nueva aurora de la humanidad, donde el único peligro es <i>no llegar a tiempo</i>.</b>

 El ser humano, acumulando destrezas y tecnologías, ha logrado la <i>'portentosa'</i> idea, y  lo peor del caso es que se lo ha creído, de que es el centro pensante  del Universo. Es  su  conciencia egocéntrica la que no le ha permitido estar a la par de la razón más elemental y objetiva, cual es la de adaptarnos, en nuestra verdadera dimensión espacial, temporal y energético-informativa, a la realidad, como relación de cambio continuado, mas allá de todo conocimiento y predicción de ciencias lineales, pero mucho más apreciable en su crisis, al evaluarse en el mundo interactivo de la velocidad y la interdisciplinariedad gnoseológica.

<p>Era de suponer que un producto del ser humano, como es la ciencia, quedara condicionado a su propio perfil y evolución. Ocurrió que la ciencia del hombre tomó su mismo perfil egocéntrico.  Lo que no se suponía era que la humanidad desviara su curso en sólo cinco mil años, transfiriendo conceptos y culturas que conducen a la degeneración de la misión del ser humano en el planeta, y como consecuencia directa, hacia su propia destrucción.

<p>Yo creo, con perdón de los seres humanos, que si los simios hablaran dirían:
“...Obsérvalos, nosotros tenemos cuatro millones de años y aquí estamos, casi  iguales; en cambio, ellos (los hombres) apenas cuentan quinientos mil años y ya  tienen el globo casi a punto de ser  destruido”.

<p>El propio desconocimiento del <i>misterio</i> de la relación de relaciones, le impidió sentirse objeto de su propia fuente, y cayó en la fatídica trampa de atribuirse todo el  conocimiento y el poder de administrador de los recursos naturales y  diseñador de rupturas bio-psico-sociales. 

<p>Sólo un progresivo deterioro, una creciente incertidumbre con acento de peligro, una demostración fáctica de escasez de recursos vitales,  podría fundamentar el criterio de solventar las necesidades con  un nuevo esquema filosófico y científico.

<p>Se tenía que encontrar una verdadera forma de visualizar esa realidad  total,  y así, ubicarnos objetivamente, con nuestros propios atributos y potestades, vicios y defectos, en el recinto infinito de la existencia. Parece ser que al encontrar esa definición, nos estuviéramos encontrando con nosotros mismos, en una identidad esencial, trascendente e inmanente con ese mismo  <i>ser total, del que somos sustancia de evolución y cambio continuo</i>. Pero el ser humano se nos ha convertido en un animalito plagado de circunstancias  y escéptico a todo aquello que, por no estar en la inmediatez de su aprehensión, se vuelve  un poco difícil y por lo tanto utópico, complicado e innecesario. Sólo interesa: <i>“En  el día de hoy y aquí”;  “Puede ser que mañana...; “Ese no es mi problema”</i>, etc.

<p>Pero toda afirmación debe encontrar un ámbito proporcional de comprobación, por supuesto, en el sentido y dirección de su postulado.

<p>Al encontrar esa <i>verdadera forma</i> de visualizar la realidad total, cuyo estudio e investigación comenzó hace cuarenta y cuatro años fecha, no se podía predecir una nueva verdad, una nueva interpretación de lo que significa la justicia, ni tampoco lo que era la realidad. No parecía tampoco conveniente decirlo, escribirlo y mucho menos afirmarlo; sería  mejor mantener la duda y asumir la táctica de dejar transcurrir, en ese corto tiempo, el escenario de las escasas posibilidades de un progreso a largo plazo, si se lograba la certeza del argumento.

<p>Sin embargo, con el discurrir del proceso investigativo y extensivo, podemos hoy, audazmente, presentar con toda sinceridad una opinión. Consideramos suficientemente causada la redefinición de realidad. Admitimos gustosos cualquier tipo de crítica o comentario que sea igualmente causado. Pero estamos seguros que con el tercer milenio comienza una nueva civilización.

<p>La filosofía es una y la ciencia también. En esa unidad se encuentra la totalidad del conocimiento, la integración del espacio, el tiempo, la energía, la información, y con estas dos últimas la posibilidad  de todo ser viviente de comunicarse  con el mundo exterior, con sus causas y efectos en  el proceso. No son ellos, con su suma o combinación, los únicos o últimos recursos, sino que todo, absolutamente todo, cambia cuando aparece la relación de macrosistemas conectados entre sí que son existenciales a todo ser. Hay una totalidad en el concepto de integralidad de relaciones, de ese cambio continuo que experimenta el mismo conocimiento de la <i>Relación de Relaciones</i>. Así surgen los nuevos paradigmas, y con ellos,  novamos los criterios dimensionales.

<p>Esa unidad y esa totalidad no tienen causa única en el conocimiento humano, sino en un conocimiento causado universalmente y con destino metahumano, en el cual sólo nos atrevemos a mencionar que la prospectiva de la raza humana es, cuando menos, una filosofía de gran sentido <i>Integralista</i>  (FI). La Filosofía Integralista está fundamentada en la pentadimensionalidad, como estrategia que acompaña la propia velocidad del cambio continuo, y mantiene el contacto con las investigaciones extensivas. Así, pudimos auto-ofrecernos perspectivas claras y proyectivas factibles, en las investigaciones que se hicieron en el campo de la ciencia interdisciplinaria, combinada con la praxis social, siempre paralela y simultánea. Siempre la extensión social nos permitió investigar más, y la investigación científica permitió extender mejor el trabajo social. Era en esa dimensión en la que se encontraba y se encuentra la verdadera docencia del <i>ser y el estar.</i> 

<p>El máximo exponente de una UNIDAD DE LA TOTALIDAD, es el <i>concepto y su presencia compleja en el escenario de los hechos y procesos humanos.</i> Desde allí nace la incesante formulación que hacemos los individuos de la especie humana, por y para penetrar en los misterios del conocimiento cósmico, que es nuestro desiderátum humano.

<p>Hemos evolucionado, con nuestros complejos mecanismos, desde ser peces en el agua, o reptiles arrastrándose por los suelos, hasta mamíferos, para generar y engendrar lo que luego nos permite erguirnos verticalmente en busca de mejores perspectivas, buscando al mismo tiempo colocar nuestros órganos de percepción más cerca de nuestro mundo inteligente y conceptual frontal, valorativo y teleológico. Hemos constituido, a lo largo de un millón de años primero, y luego de cincuenta mil  años más, los símbolos, los signos; el lenguaje, primero fonético, luego visual, táctil, proyectivo; los códigos lingüísticos, los electrónicos y el apoyo incesante  de las más variadas formas de percepción remota, etc. Todo ello porque hemos generado la plataforma adecuada para impulsar el Concepto humano de realidad, llamémoslo Concepto (humano) Básico. Pero la ironía toca la puerta de lo increíble: sabemos extraordinarias cosas científicas de los detalles más específicos, que nacen de las inmensas inversiones de capital y conocimientos que tocan el mundo de la guerra, el comercio y la industria del confort. Pero no sabemos evitar la violencia, el hambre y la ignorancia del 75 % de toda la humanidad.    

<p>Esta unidad filosófica es la que integra conocimientos de todo <i>ser humano</i> para ir en busca del <i>mayor poder</i> y <i>poseer</i> posibles, haciéndolo en proporción al orden y nivel de complejidad al que pertenece en espacio y tiempo, pero siempre en su propia compensación, con tendencia al menor esfuerzo, con la mejor información, en el menor tiempo y con el menor y mejor recorrido espacial. 

<p>Esa unidad causada es  un tercio en el  superhombre  consciente y espiritual, en contacto con el infinito ONTO; un  tercio con la relación que se formó del propio infinito universal en el espacio y tiempo, convertidos en evolución trascendente de dominio y conocimiento de PODER, que formaron esa unidad proveniente del concepto cósmico  y esencial de <i>ser</i>, del <i>poder</i> y del dominio de trascender, y de lo inherente e inmanente al <i>estar</i>, sobre el cual se materializó  el  CORPUS humano. Esa trilogía se relacionaba con su propia y genuina unidad de presencia, transferencia y transformación: El Concepto Básico.

<p><div align=center><img src="fundamento filosofico.gif" width=425 height=556 border=1></div>

<p>El <i>concepto básico como unidad de los Sistemas Inteligentes</i> no ha podido aún ser empleada en el concierto de la paz y la justicia social. Sabemos de la existencia de los sistemas inteligentes. Pero también son evidentes los sistemas   “no inteligentes”.  Entonces, sin quejarnos del pasado y sin reclamar la violencia, la ignorancia y la miseria, es necesario que adoptemos rápidamente  posturas inteligentes en el comienzo oportuno del tercer milenio. Es con ese concepto básico, utilizado a plenitud, con el que se puede saber, saber hacer y enseñar al mundo de los pueblos pobres, el conocimiento y la praxis de los sistemas psico y sociomotivadores de la comunicación, información, inteligencia social y activación.

<p>Debemos estar claros de que esta unidad, también tiene su evolución, más por aceleración del entorno, que por sus propias conexiones.  Coincide en todas sus partes con el criterio de investigación extensiva, que hemos acometido y sostenemos. No existe la evolución ni la institucionalización del concepto ni del valor que éste genera, si no concurren, se  refuerzan y se le adecúan las experiencias, con la perfectibilidad implícita en ellas.

<p>En otras palabras, la investigación como utilización del concepto, no adquiere validez en los procesos y sistemas, si no es de alguna manera utilitaria y optimizable . 

<p>Debe comprenderse entonces (porque es necesario)   que al pasar de la Filosofía Integralista, de la Teoría del Conocimiento Trialéctico, de la Sistemática Interdisciplinaria, y de la Dimensión Cualitativa a la Metodología Compleja, y más acá de todas ellas existen leyes de la naturaleza que son universales pues denotan un gran sistema universal, un sistema de todos los sistemas o “Sistemática” que es esencial decodificarlo en beneficio de la ciencia y la filosofía vital. Solo se puede   propiciar  el verdadero  desarrollo social a través de los  sistemas inteligentes, al ser  implementados  en la base social; que los factores de cambio, a su vez generadores de <a href="#" onMouseOver="stm(Text[0],Style[1])" onMouseOut="htm()" class=tip2>potenciales sinérgicos</a> y de <a href="#" onMouseOver="stm(Text[1],Style[1])" onMouseOut="htm()" class=tip2>potenciales sintérgicos</a> de mejoramiento progresivo de la calidad de la vida, sean debidamente estudiados, y que los medios de difusión y divulgación para las masas colaboren con ese fin a través de sus fascinantes experiencias en el cine, la televisión, la prensa y la radio.

<p>Estos sistemas integrados, no son, además, puntualmente imperativos, simultáneos ni completamente localizados, sino más bien un tejido progresivo, elástico, persistentemente proyectivo y acumulativo, de redes fácilmente informatizadas, por estar todas relacionadas fácticamente. En Mapas Sociales pentadimensionales,   se ubican con toda claridad las necesidades sentidas y las capacidades ofertables para el beneficio  de  la población de las áreas afectadas.  Las  potencialidades y deficiencias  de las comunidades  adquieren un mejor rango práctico, cuando son conocidas por sus actores dentro de un sistema de información. 

<p>Sería poco menos que inútil mencionar estas proposiciones, si no existiera un verdadero contenido científico, sistemático y metodológico, que aunado a un marco conceptual general, puede impregnarse de todas las funciones intelectuales y operativas  de los entes que pueden ser, implícitamente, actores e invitados a tal cruzada de importancia tan trascendental.

<p>Todos los razonamientos que aquí se exponen, son sólo algunos de los muchos que podríamos mencionar y explicitar, si real y   exhaustivamente domináramos el arte de redactar y transmitirlos eficientemente.  Aunada esta suerte  a la difícil complejidad de destruir un mundo de simulaciones que en nuestra sociedad de consumo,  le rinde  tributo a los circunstancialistas, accionistas y gestores de la apariencia y del gradual deterioro de la verdad.    
 
 <p>Para precisar las ideas filosóficas básicas que dan origen a una explicación básica, nos referimos a los gráficos siguientes:

<p><div align=center><img src="fundamento filosofico 2.gif" width=425 height=436 border=1></div>

<p>En ellos podemos apreciar en la primera, al “SER” , a través del espacio-tiempo buscando el mayor poder y poseer posibles a través de los ciclos que van desde la dinámica socio-política, generando conceptos, hacia la dinámica socio-económica para regresar al propio sistema del conocimiento y la acción. En otras palabras son los ciclos que recorren desde el conocimiento hacia el uso y de regreso al nuevo concepto, una vez generada la experiencia del hacer. 

<p>En la segunda se aprecia igualmente, al ser pero ya concretado en  el ciclo de llegar al poder por el saber y al poseer por la vía del hacer, completando ciclos del saber, del saber hacer y del saber, hacer saber (saber enseñar), como partes de las dinámicas que encierran en su existencia categorías y aspectos sectoriales que se podrán observar en la matriz sectorial .  Ello ocurre en lapsos cortos, medianos y largos de interacciones entre la información y la energía, la primera transformada en conceptos y la segunda en usos. Ellos son fuentes respectivas del poder y del poseer.

<p>Este proceso confirma la esencia del ser, con la trascendencia del poder y la inmanencia del poseer, en ese juego natural y universal que conforma la realidad.

<p>Es al mismo tiempo que la realidad se puede apreciar y por lo tanto conocer de su existencia, no como algo sencillamente perceptible para la mente humana con sus teorías objetivas o subjetivas del conocimiento, sino como una gran esfera cognitiva que representa todo cuanto existe y es cognoscible.

<div class=menu><table width=100% border=0><tr><td align=left width=33%><a href="introduccion.php">Introducción General</a></td>
	<td align=center width=33%><a href=index.html>Indice</a></td>
	<td align=right WIDTH=33%><a href="teoria.php">Teoría del Conocimiento Trialéctico</a></td></tr></table></div></div>
</body>

</html>
