<!doctype html public "-//w3c//dtd html 3.2//en">

<html>

<head>
<title>Dimensión Cualitativa - Parte 6</title>
<link rel="stylesheet" type="text/css" href="estilo.css">
<SCRIPT language="JavaScript1.2" src="../../js/main15.js" type="text/javascript""></SCRIPT>
</head>

<body>

<DIV id="TIP" style="visibility:hidden;position:absolute;z-index:1000;top:-100;"></DIV>
<SCRIPT language="JavaScript1.2" type="text/javascript" src="introduccion.js" ></SCRIPT>

<div class="subtit" style="position:absolute;top:2px;">
La Dimensión Cualitativa
</div><br><br>

<div id="cuerpo" style="width:570px;">

<h2>PARTE VI: LA FUNCION INTENSIDAD</h2>

<p>El ser humano es <i>actual</i>. Vive su <i>hoy y aquí </i> sin  saber lo que eso significa realmente. No tiene, en general, idea clara de lo que es el espacio, ya que lo ve como un recurso tridimensional. Tampoco tiene una buena e inteligente consciencia  de lo que es el recurso no renovable del tiempo .

<p>Más adelante significamos la importancia del <i>Presente Dinámico</i>. Pero fundamentalmente el ser humano es potencial de humanidad. El hombre actual acumula los efectos y relaciones parciales del pasado, pero nunca la ciencia le ha dotado de una metodología para evaluarse en relación con sus sucesivos ambientes y órdenes sociales respectivos. El pasado es un proceso secuencial de sucesos encadenados al complejo de infinitas variables en ese llamado <i>Presente Dinámico</i>. Para definir la función <i>Intensidad</i> tenemos que penetrar el concepto básico de <i>Presente Dinámico</i>. 

<p>El concepto de Límite Matemático o Derivada en un sitio y en un momento dado (espacio-tiempo con dirección y sentido longitudinal) nos ayuda a comprender la relación con el  infinitamente pequeño energético-informativo, del que somos sujetos integrados. También nos ayuda a interpretar el  estar  dirigidos y orientados en forma continua por diversos vectores culturales, políticos, económicos, etcétera, que nos permiten ser capaces de saber y   leer  la realidad, como proceso de cambio la expresión exacta de cada acción o  movimiento. Ese movimiento es de relaciones permanentes entre espacio-tiempo, micro-necesidades y micro-capacidades, todas las cuales constituyen en el hoy y el aquí, el  Presente Dinámico, en la capacidad de conocer, identificar y ejecutar acciones  <i>en forma continua</i>.

<p>Ese infinitamente pequeño se representa también por el signo Alfa, que se expresa  como símbolo y derivada del ciclo que conforma todo microcambio. 

<p>A los efectos prácticos, el incremento de la <i>intensidad</i> es el crecimiento de la magnitud  del radio que se extiende en forma de movimiento de circunvalación alrededor del eje espacio-tiempo y causa-efecto (<i>paso de tornillo</i>), incrementando su diámetro  segundo a segundo, sitio a sitio, en la misma medida y proporción en que ingresan las unidades de  información y energía al sistema. 

<p>Es lógico pensar que la proyección de ese crecimiento paulatino del radio, genera un conoide como el que se muestra en la figura anexa, ya que si no existiera un incremento en esos sistemas de información y energía, la expresión gráfica sería un cilindro, o si el incremento fuera siempre el mismo, por unidad de tiempo, sería sólo un cono. Pero siendo la realidad cambiante, y dirigiendo los sistemas hacia fines conocidos o determinables, la vertiente <i>información acumulada</i> y <i>energía acumulada</i>, siempre tienen y representan una magnitud superior a la anterior, con lo cual se subtiende el sólido imaginario virtual <i>conoide lugoviano de rotación progresiva de todos los sistemas conscientes</i>.

<p>Mientras se desarrolla la función <i>profundidad</i>, anteriormente descrita, se van generando los incrementos de información y energía en sendos movimientos gráficos a escala, llamados, cuando se presentan los proyectos, <i>infogramas</i>  y <i>energramas</i>. 

<ol>
<li><b>Infogramas:</b> son visiones conoidales regulares en los que  se toma en cuenta, exclusivamente, el ingreso de la información al sistema, como potencial sinérgico. Representa sólo el ingreso de información UCO.

<li><b>Energramas:</b>  son visiones conoidales regulares en los que se toma en cuenta exclusivamente el ingreso de la energía al sistema como potencial sintérgico. Representa sólo el ingreso de energía UCO. 
</ol>

<p>La representación gráfica de ambos permite interpretaciones para el establecimiento adecuado de la autogestión, la cogestión, y la gestión gubernamental de programas públicos y privados. 
	
<p>En síntesis, el conoide es un sólido con coordenadas cualitativas ( sistemas) donde  su altura  representa la función de perspectiva  trascendente longitudinal: <i>“profundidad”</i> o Sistemas  ZZ´;  la función trascendente transversal en movimiento rotatorio gradual, representa la  <i>“Intensidad”</i> o sistema  XX´  y YY´;  y  la secuencia y frecuencia progresiva y acumulativa de los ciclos representa la <i>“Velocidad”</i>  o  sistema de circunvalación sobre el eje ZZ'.

<p>Para la conversión de objetivos en  resultados concretos y programados en espacio y tiempo, dentro del direccionamiento planificado, se deben superar los desniveles orgánicos e integrados de toda la situación-problema,  desde el vértice o comienzo hasta el término pautado como resultado a lograr.  El vencimiento de esa distancia está  representado por los ciclos con la frecuencia adecuada para que dicho logro sea coincidente con los espacios y tiempos predeterminados y el rendimiento proporcional al costo, esfuerzo y transferencia cognitiva.

<p>Estos gráficos pueden verse  en perspectiva,  planta o perfil longitudinal,  pero su análisis desde cualquier punto de vista, debe observarse como una homologación y analogía lógico matemática de la Dimensión Cualitativa. La prolongación del eje ZZ y de los sistemas XX y YY, describen la clara visión de la pentadimensionalidad,  constituyendo un sistema complejo que representa la propia identidad de la mente humana.

<p>Tenemos que pensar que cualquier información puede ser útil, o por el contrario, bien puede ser basura, dependiendo de que esté dirigida a una vertiente, variable, objetivo, meta o actividad determinada, o que más bien la desvíe. También de que la información debe ser completa, o sea que contenga  los elementos factores  que definen el  <i>Dónde, Cuándo, Con Quién, Con Qué y Para Qué</i> meta u objetivo  son capturadas y procesadas.

<p>También tenemos que hacer depender los incrementos en el sentido de la <i>oportunidad</i> (conveniencia hoy y aquí). La oportunidad tiene una posibilidad, que al buscarla,  permite asignarla de acuerdo a la función  longitudinal sobre el eje ZZ “profundidad”, en un sitio y tiempo adecuado y concurrente con los objetivos y metas programados.

<p>El potencial generado al acelerar la captura de información, consecuencia derivada de los procesos autogestionarios de la población organizada, que la motoriza,  se traduce en un incesante  aumento  de capacidades insertas en los seres humanos de esa misma población, y por lo tanto con la captura de la energía subyacente en ellos. Esos potenciales sinérgicos (información en el tiempo) y sintérgicos (energía subyacente en el espacio territorial) se expresan en una transferencia constante de  imágenes, sonidos, conceptos, olores, sensaciones, armonías, paisajes, actitudes motivadas y percibidas que constituyen conceptualizaciones muy conscientes de juicios de relación y valor, referentes a las  necesidades y capacidades de la gente, etc. 

<p>Esas transferencias tienen dos sentidos: la que percibimos con la impresión e interpretación que ingresa a nuestra psiquis y la que nosotros otorgamos, inducimos y exhortamos a ejecutar a otros, que incluyen la formación estructural y funcional pre-diseñada en los proyectos y programas, incluyendo  a nuestra  propia naturaleza motivacional, con nuestros propios fines y metas.

<p>Todas nosotros, como las personas y las  cosas en movimiento de sentido concurrente a los  programas establecidos, producimos ciertas transformaciones que se procesan favorablemente en nuestro cuerpo social, en las   relaciones de poder y en  nuestro  entorno,  o sea en nuestro mundo sensible,  conceptual y valorativo, y a través del espacio-tiempo, donde logramos crecer y desarrollar nuevas formas de proceder, acumular, proyectar,  sobre todo, nuestro sentido potencial y    <i>ser prospectivo</i>.  

<p>La prospectiva es el quinto paso que damos cuando desarrollamos toda la potencia del <i>ser</i>. La  unidimensionalidad no existe ni en la práctica ni en la teoría;  la bidimensionalidad está enmarcada en la representación que muestra un mapa, plano, croquis, diagrama, esquema, etc. La tridimensionalidad abarca el espacio como recurso utilizable en sus tres formas de verse, tanto el largo, ancho y profundo, perceptual y perspectivamente hablando (hoy en día están de actualidad los mapas tridimensionales digitalizados).

<p>La tetradimensionalidad (relación cualitativa de dimensiones) o continentalización, está en la programática compleja del macrosistema espacio-tiempo, asignada a una determinada circunstancia, condición y término, que generalmente se identifica con un tipo de proyectiva (acotamos la diferencia entre tetradimensión y cuatridimensión de la teoría de la relatividad: aquella es cuantitativa y esta cualitativa). La proyectiva, a su vez, es una forma secuencial de sucesivas perspectivas o visiones en el espacio-tiempo, que sugieren transformaciones, tal cual como puede hacerse al pasar de una serie de fotografías a una película en movimiento. La frecuencia  y la secuencia exhortan a una vivencia que potencializa nuestro ser   en todos sus ciclos, tanto percibidos sensiblemente, como conceptuales y de activación. Todo depende de un diseño apropiado.

<p>Y por último, la pentadimensionalidad no equivale a cinco dimensiones interactivas sino a una simbiosis existencial de la propia realidad que abarca la acción humana con la determinación de sus necesidades sentidas y capacidades ofertables, en forma de hermenéutica y simbología  dirigidas con inteligencia hacia todo el proceso. Este  puede ser convertible en sistema,  y propiciar  mental, técnica y logísticamente  una situación, al prestar atención a una intención específica, ejecutando acciones concretas dirigidas  hacia metas y objetivos predeterminados.

<p>En estas metas u objetivos predomina una lógica acumulada y objetiva de la información, la inteligencia, la reflexión y la  metodología que se utiliza para focalizar individualidades y colectivos necesitados, y al mismo tiempo, oferentes de diferentes potencialidades

<p>La potencialidad del ser humano no se queda allí, en un concepto; su inteligencia mejora aún, mucho más, con  la inteligencia colateral de la ciencia aplicada, y va cediendo  en esa acumulación progresiva a los sistemas de tecnología inteligentes, que han elevado la potencia a la enésima proporción de la electrónica, la percepción remota y las telecomunicaciones dirigidas desde un programa dado. Las plataformas hoy en día trabajan en tiempo real y con un monitoreo apropiado; trabajan también en espacio real. Pasar a los mapas pentadimensionales constituye la antesala de los mapas sociales y de los futuros y  próximos Sistemas Autonómicos: ya es sólo la adición de tecnologías sociales adecuadas y construidas a escalas concurrentes con dichos objetivos y metas, la que nos separa de una nueva y mejorada cuestión paradigmática y civilizatoria.. La actualidad (muy acelerada) nos obliga a acudir a la tecnología como medio de neutralizar la acelerada descomposición, pero debe ser una tecnología de punta, con información e inteligencia incorporables fácilmente al sistema, exactamente como son esos mapas sociales y útilmente pentadimensionales.

<p>Lo que aparentemente ha sido un adelanto, como puede mencionarse en  las actuales tecnologías de una sociedad eminentemente de lujo y consumo, se convierte ahora en una verdadera y cuasi fatal inversión entrópica. El incremento sistemático de lo que deberían ser  <i>valores</i>, se ha ido desviando hacia el <i>antivalor</i> (donde la circunstancia prevalece sobre la trascendencia) del intercambio masificante y agobiante en el   abuso de la concentración económica del poder compulsivo del convencionalismo social, que nos ha convertido en una escueta sociedad de trivialidades.

<p>Todo, absolutamente todo, salvo los sistemas verdaderamente inteligentes a largo plazo, han sido absorbidos por la potencialidad material en la satisfacción de los sentidos de percepción: la visión, la audición, el gusto, el olfato y el tacto. Ellos han afectado a la psiquis y ésta, aislada del condicionamiento de una escala de valores, ha quedado indefensa ante el ataque concentrado de los mass-media. La juventud del mundo está siendo  convertida paulatinamente en un plasma de descomposición  social, sin sentido de largo plazo.

<p>La función <i>intensidad</i>  está, a su vez, convirtiéndose en un sistema de ingreso de información inútil, neutra o basura, con desarticulación de la inteligencia en el  desarrollo de muchos   pueblos, donde abundan la ignorancia y la miseria;  desgraciadamente,  esos son  los  protagonistas máximos de los procesos de descomposición. Hoy, es difícil predecir si la humanidad agobiada por enfermedades y hambrunas tocará a su fin de esta  manera paulatina, pero incruenta, o si, por el contrario, podemos ser víctimas de un ataque esquizofrénico  de esos muchos locos  con poder de alta tecnología que pueden disparar, cuando menos lo pensemos, un “lumínico” de  destrucción encadenada.

<p>La Dimensión Cualitativa, como totalidad del control, evaluación y seguimiento de los procesos de la  realidad cambiante, disminuye su <i>calidad axiológica</i> cuando en detrimento de los procesos de <i>intensidad</i> y de <i>velocidad</i>, la sociedad acumula puntos en la olimpíada de la entropía social; en cambio ofrece una verdadera composición y activación social <i>por sistema</i> en la medida en que concurra, se adecúe y se extienda al cuerpo social. Desde allí podemos inferir lo importante que es el eje <b>ZZ</b> en el que por una estrategia inteligente hacemos coincidir objetivos-metas  y resultados potenciales,  con el espacio tiempo, a velocidad de diseño.

<p>Es esa <i>intensidad </i> la que está afectada  por el incremento inusitado del uso de la información como <i>basura</i> y la energía como desgaste, ambas como factores <i>entrópicos</i> en pos de un fracaso ontológico. Se trata, en suma, de no plegarse a una frecuencia veloz, sin que tampoco podamos remediarlo como fenómeno social,  a no ser que sepamos como cambiar los parámetros  de la descomposición por los de composición, y al hacerlo actuemos coherente y eficientemente, fundamentándonos en la propia velocidad del cambio para ofrecer nuevos formularios de psico y socio motivación al logro por <i>sistema</i>. 

<p>También nos atrevemos a decir, que <i>si el mal cunde sin remedio aparente a la vista</i>, sería peor  la ignorancia sobre como decodificar los impulsos de ese gran mal.  Desde la visión de esa oscuridad gradual, hasta  la perspectiva y prospectiva de la propia realidad total, nos atrevemos a implorar, a todo efecto, un mayor conocimiento de ella, como primera terapia para emprender el regreso a la normalidad social.

<p>Hasta ahora hemos hablado del incremento del sistema actual de la información  <i>'materializante'</i>,  pero su lógica compensación, que es  la materialización de las ideas, sucede como consecuencia de la energetización de una modernidad que permita,  por la activación  del propio sistema  la sensibilización de un bienestar que pueda ser percibido en la medida de ser ejecutadas sus acciones (espacio y tiempo reales). Es decir, que los ciclos de descomposición del equilibrio conceptual se transformen en sistemas inteligentes. La misma ignorancia o incremento inconsciente del peligro, producen un mayor peligro. En fin, pareciera que ha llegado el momento, no sólo de cambiar  paradigmas, sino de activar una nueva forma de prospectar nuestro futuro.

<p>A <i>mayor incremento</i> de la información inútil, neutra o basura, surge con  un mayor intercambio sectorial incontrolable por el momento, y profusamente,  la contrainteligencia del subdesarrollo,   factor de descomposición cíclica. El intercambio y transferencia de los conocimientos sin tellus produce a mediano y largo plazo, actividades convertibles algorítmicamente en factores de enajenación colectiva. Esa situación compleja de problemas interactivos, sólo es manejable con sistemas inteligentes que, en base a buenos sistemas de información social, puedan activar fórmulas prácticas de bienestar por autogestión y co-gestión. 

<p>Es un axioma que la mayor relación entre la conciencia y la experiencia se registra con el resultado obtenido en cada ciclo de transferencia de la función <i>Intensidad. Ese ciclo significa transformación.</i> Quizás ese sea el único factor que todavía permita que subsistamos y logremos convivir en este pequeño planeta que se nos está volviendo loco. Si nos damos cuenta de la velocidad y aceleración de la interactivación de sesenta y dos variables de descomposición, en contraposición con las escasas y registradas variables de composición, bien podríamos diagnosticar que nos quedan pocos ciclos (normalmente de siete años cada uno) de vida útil, y quizás, por un milagro de la conciencia kósmica, lograríamos sobrevivir un poco más.

<p>El gran problema de la humanidad es, en términos generales,  la continuada interacción entre las variables de descomposición social. Estas cubren exactamente los mismos ciclos que desde lo social giran en torno a la educación, promoción, inteligencia, políticas, formas de administrar los recursos, energía, información, espacio y tiempo; la economía y las finanzas, la producción y comercialización, los servicios y la infraestructura, el ambiente y la salud, para regresar irreversiblemente a lo social.

<p>Permítasenos ser reiterativos. Por ejemplo, cada gramo de droga incorporado al cuerpo social por los drogadictos produce un estado anormal de comportamiento personal vinculado a la propia  escasez de conceptos útiles y valores; se promueve así la antisociedad, se afecta la inteligencia, la  fisiología, con la  disminución del  apetito en detrimento de  la nutrición; en  la conducta intrafamiliar en el sentido del mal  ejemplo, del desorden y del abuso de autoridad; con la ausencia de la moral,  con el desprestigio social, con la conducta sexual, con la participación de una falta de administración  económica en las relaciones comunitarias, en la pérdida de capacidad  para el trabajo, con el orden normativo hacia las estructuras del orden ciudadano y la lógica contaminación del ambiente y la salud. Todo ello, suponiendo que el consumo no traiga otros efectos colaterales más profundos. El drogadicto es, en suma, un factor de ignorancia por la falta de estudio; de miseria por la falta de empleo y producción, por el daño a la infraestructura y los servicios del desarrollo familiar; por la ausencia de interpretación que acompaña al escenario respectivo; por el quebrantamiento de normas éticas, valores y convencionalismos sociales; por la ausencia de una administración adecuada del espacio; de la economía familiar que se ve afectada por un gasto inusitado, por la contaminación en cadena y por la incapacidad psico-sociológica para dirigir y responsabilizarse por un grupo. Hay que multiplicar cada gramo de droga, por las doscientas ochenta toneladas, o doscientos ochenta millones de gramos de drogas para su consumo durante un año que pasan por Venezuela, de los cuales cerca del 40% se quedan sembrados aquí.

<p>Si computamos la pérdida de tiempo útil, de energía dirigida a la producción de valores de intercambio económico, del excesivo gasto de la nefasta inversión, de los factores psicológicos, sociales, políticos, normativos, financieros, ecológicos y socio-sanitarios; de la desinformación y la desactivación, afirmaríamos que se estaría gestando una pérdida encadenada fatalmente a la destrucción del individuo, a la afectación grave de su núcleo familiar, al de la comunidad vecinal, y  también se está afectando gravemente la vida de los procesos municipales, regionales , nacionales e internacionales.

<p>Todo ello sin suponer confinamientos, hospitales, cárceles, enfermedades, accidentes  y muertes. Aquí debe reiterarse también que simultáneamente funciona la variable <i>profundidad</i>  del efecto perturbador; la  <i>intensidad</i> de la desconexión familiar, social, etc, y la <i>velocidad</i> del efecto que se  trasmite en la sangre, en el lenguaje, en las costumbres, en el patrimonio cultural, en la economía y en las políticas de desarrollo. El derrumbe sin regreso de los pueblos, no tiene que venir necesariamente de un solo hecho  del hombre o de la naturaleza; bien puede ser, tal como sucede ahora, un proceso progresivo y acumulativo de descomposición interactivada.

<p>Pero sobrevienen otras variables: la miseria, el hambre, la ignorancia, la irresponsabilidad, la corrupción, los delitos contra las personas, los bienes materiales y los morales, la promoción del vicio y la desarticulación jurídica y política de las instituciones locales.

<p>El peso de un solo drogadicto es inconmensurable. Pero como son cadenas de drogadicción que afectan la producción, el comercio, etcétera, etcétera, no  puede dársele magnitud a la interacción de la droga con las otras variables de descomposición que suman, sesenta y dos en total. 

<p>Lo que si se puede asegurar es que corren paralelamente el sida (VIH), las enfermedades sexuales,  el porcentaje elevado de los delitos y   todas las faltas administrativas y de corrupción. 

<p>De allí la importancia de un esquema de reconstrucción sistemática e integral que permita generar esfuerzos dirigidos a la recolonización de cada país y de todo el planeta. No deja de ser interesante observar  la <i>Plataforma Conceptual</i> que se encuentra después de las funciones trascendentes. Allí se puede apreciar, objetivamente, como la apertura del conoide (figura analógica pentadimensional) produce una información y un flujo de energía que tiende hacia el infinito, cuando el espacio-tiempo tiende a cero. Ese gráfico universal, de semiótica con analogía lógico-matemática, cuantifica la tetradimensionalidad del espacio y el tiempo con sistemas de información e inteligencia en los mapas sociales, tal y como lo veremos en el “Municipio Inteligente”.

<p>Allí se clasifica como <i>neutra</i> una ética del desarrollo. ¿Cómo podríamos observar ese mismo gráfico, si admitiéramos la hipótesis de  que la dinámica socio-política que se observa en el lado superior del mismo, se siguiera desplazando o disminuyera su ritmo de compensación con la dinámica materializante de carácter socio- económico?  La verdad es que, en este momento y desde este sitio, estamos implorando un incremento en los sistemas de inteligencia con sentido de subsistencia y convivencia, para así poder llegar a la sobrevivencia y luego a la supervivencia del ser humano.  

<p>Es muy lamentable,  que este cuadro de la actual situación, un tanto desolador,  no fuera comprendido, o que de serlo, no produjera efectos prácticos; pero lo que sería dramáticamente absurdo es que   la incomprensión del mismo fuera adjetivada como material de simple referencia o <i>ilusorio</i>. Aquí debemos destacar nuevamente que la mejor credencial de este esquema es el haber acumulado la investigación extensiva con su proporcional captación de escenarios especialmente en Venezuela, guardando el más prudente silencio antes de llegar a la certeza completa para entonces presentarlo como una  solución inteligente y veloz.

<div class=menu><table width=100% border=0><tr><td align=left width=33%><a href="profundidad.php">Función Profundidad</a></td>
	<td align=center width=33%><a href=index.html>Indice</a></td>
	<td align=right WIDTH=33%><a href="velocidad.php">Función Velocidad</a></td></tr></table></div></body>

</html>
