<!doctype html public "-//w3c//dtd html 3.2//en">

<html>

<head>
<title>Dimension Cualitativa - Introducción</title>
<link rel="stylesheet" type="text/css" href="estilo.css">
<SCRIPT language="JavaScript1.2" src="../../js/main15.js" type="text/javascript""></SCRIPT>
</head>
</head>

<body>
<DIV id="TIP" style="visibility:hidden;position:absolute;z-index:1000;top:-100;"></DIV>
<SCRIPT language="JavaScript1.2" type="text/javascript" src="introduccion.js" ></SCRIPT>

<div class="subtit" style="position:absolute;top:2px;">
La Dimensión Cualitativa
</div><br><br>

<div id="cuerpo" style="width:570px;">

<h2>PARTE I: INTRODUCCION GENERAL</h2>

<p>La DIMENSION  CUALITATIVA (DC) es un concepto básico que denota la forma de controlar, ejecutar, evaluar, mejorar y hacer el seguimiento de  nuestra vida y de la realidad  que nos rodea.  Explica el cambio continuo en un proceso complejo  que entendemos cuando lo convertimos en <i>Sistema   Inteligente (Ver Cap.VIII del próximo libro “La Dimensión Cualitativa”)</i>: específico,  social, político,  económico, y en términos generales, en aquello que constituye la universalidad. 

<p><i>Satura</i> los contenidos de la Geo-Historia (Sistema Espacio-Tiempo) y de las ciencias interdisciplinarias que tratan de la relación conceptual entre las diferentes disciplinas, conjuntamente con las ciencias y la tecnología. En cambio, nacen diversas interacciones que producen nuevos conceptos científicos, de aplicación necesaria y posiblemente urgentes:  la ecología humana, la físico-química y biología del conocimiento, la sinergia de la producción, la sintergia de la inteligencia, la nanotecnología del lumínico, la filosofía del cosmos, la neuro-lingüística del proceso social, etc.

<p>La Dimensión Cualitativa nos trae a un nuevo sistema de investigación, que se aplica y extiende simultáneamente en todo nuestro entorno cognitivo y físico. Al aplicar  dicho  sistema podemos hablar, como una de  sus  características, de  la <i>secuencia de imágenes fotográficas que como una   película se reproducen</i> y   se impulsan con el cambio continuo de la realidad  (Investigación Extensiva) lo que permite obtener  una secuencia   de la realidad de ese  mismo cambio continuo. Es así como se rompe el actual paradigma científico del <a href="#" onMouseOver="stm(Text[0],Style[1])" onMouseOut="htm()" class=tip2>positivismo</a>. Nos encontramos, entonces, con un estadio superior a las multiciencias, a la <a href="#" onMouseOver="stm(Text[1],Style[1])" onMouseOut="htm()" class=tip2>interdisciplinariedad</a> convencional, a la <a href="#" onMouseOver="stm(Text[2],Style[1])" onMouseOut="htm()" class=tip2>transdisciplinariedad</a>, etcétera, connotadamente diferente a ellas. Contiene la premisa de <i>Sistema de Sistemas</i> o  SISTEMATICA DE LA INTERDISCIPLINARIEDAD.

 <p>Sobre este esquema general, yace  la nueva ciencia. Constituye el sistema gnoseológico de toda investigación-extensiva en sus propios ciclos y secuencias. La relación de todas las  disciplinas queda subsumida en la premisa de la sistemática y por lo tanto la investigación que se realiza rebasa la relación disciplinaria porque transforma el paradigma actual de todo el conocimiento humano, a la velocidad del cambio de la realidad.

<p>Se trata de despejar, en forma contundente  y definitiva, la simulación actual de la ciencia parcial y de un sinnúmero de teorías que, sin ser falsas, sólo descubren parte de la verdad científica <i>inercial</i> (conceptos que no aceleran procesos) lo que es un verdadero acertijo. Estas  son, justamente las que <i>NO CONDUCEN AL CONOCIMIENTO DE LA REALIDAD COMO CAMBIO CONTINUO y ACELERADO</i>. Es también una verdadera calamidad que toda una civilización, y quizás la humanidad entera,  pueda llegar  a perderse  por ignorancia,  negligencia e imprudencia científica y filosófica.

<p>En tal virtud la Dimensión Cualitativa otorga el permiso para insertarse en los niveles de la <i>Realidad</i>, cosa que nunca se había logrado. Es ahora cuando comienza el <i>COMO LOGRARLO</i>.
	
<p>Cabe recalcar que el cambio continuo tiene la mayor importancia al diferenciarse, como lo veremos a lo largo de estos contenidos, de las ciencias actuales, observadas como escenarios inerciales y juicios simples de relación. Para estudiar la realidad humana y toda realidad, era necesario, <i>repetimos</i>, sistematizar el conocimiento humano dentro del conocimiento universal; el concepto humano  en relación con el koncepto cósmico; no seguir desconociendo la relación de relaciones entre los sistemas  espacio/tiempo, energía, información, causa y efecto. Tampoco hacerlo <i>SIN TOMAR EN CUENTA LA VELOCIDAD</i>  de las transferencias orgánicas e integrales. Es esencial, inherente y trascendente al ser humano la relación espacio/tiempo, o sea, la velocidad y la aceleración.

<p>Cuando decimos <i>Dimensión Cualitativa</i> estamos hablando del manejo, en nuestro provecho, de ese cambio continuo, veloz y acelerado que sufrimos y en  el que nos movemos todos. Es, pues,  movernos a la velocidad del cambio, como  realidad  de la relación de relaciones que somos y donde estamos, <i>cambiantes</i> (en el “hic et nunc”). La nueva ciencia cuya característica principal es movilizarse en todo el escenario real, se fundamenta, por lo menos, en   la velocidad de su  propio <b>cambio conceptual</b>.

<p>Todo el proceso cualitativo en los escenarios de la ciencia actual, tanto por sus conceptos, coordenadas, funciones y  referencias, como por sus marcos teóricos y metodológicos, se fundamenta en un solo principio definitorio de  <i>Realidad</i>, que separa sólo fácticamente, o por lo menos, sólo vincula linealmente los sistemas de espacio, tiempo, energía, información, causa y efecto. En cambio, la nueva ciencia se mueve en un escenario integrado, total, de carácter unívoco y  <i>pentadimensional</i> (agregadas al espacio-tiempo la dimensión energético-informativa con su direccionamiento natural).  Hay un solo conocimiento universal y una sola ciencia. Volvemos a iniciar la enciclopedia de la ciencia única que tímidamente expusiera Otto Neurath.  La  expresión de unicidad bien  puede matizar sectoriales o sub-sectoriales, relaciones, derivas, integraciones e interactivaciones, sin perder su autenticidad; su nivel puede ser abstracto, semi-abstracto o concreto. Su objeto puede ser diverso, pero es una sola, y queda circunscrita a la verdad en movimiento y con ella hacia la verdadera realidad como proceso de  cambio. Ella, en la sabiduría universal, conlleva e interpreta  los distintos órdenes, niveles y complejidades de la existencia.  La Dimensión Cualitativa como parte operativa de la Relación de Relaciones, o Trialéctica, explica la importancia de aquel conocimiento que incide en esa realidad y que regresa  al conocimiento en pleno movimiento.

<p>En el mundo de la nueva ciencia, la Dimensión Cualitativa,  pentadimensional, ocupa sin lugar a dudas, el prólogo existencial o  primer capítulo necesario, por la sencilla razón de que toda la investigación científica, trata de encontrar la verdad de un hecho, proceso o acontecimiento, y entonces, tiene que instalar sus premisas sobre la necesidad de buscar soluciones prácticas, a la velocidad de los problemas, con base en los recursos conceptuales del conocimiento y la inteligencia humana, todos en relación continua de cambio, con los instrumentos, tecnologías y  materiales disponibles para transformarse  en un <i><b>Sistema de Sistemas</b></i>. 

<p>Además, los recursos y los sistemas en general, para ser útiles, completos y sobre todo oportunos, tienen que ser controlados y evaluados <i>con una velocidad mínima, igual o mayor que la de su propio cambio, y es necesario que sea mayor que la incubación, generación y desarrollo de los problemas</i>.  ¿Cómo podemos hacerlo? ¿Controlar, evaluar y hacer el respectivo  seguimiento? Solamente con   un método pentadimensional, sistemáticamente interdisciplinario, que penetre en esas verdades cualitativas de la realidad  actual como un proceso de cambio continuo.  Pareciera un enigma aquello de decir que en el millón de años que marcan los ciclos antropológicos no nos dimos cuenta de que nuestra actuación en el planeta conlleva a justificar nuestra existencia y nuestros logros sobre  <i>una velocidad mínima, igual o mayor que la de su propio cambio...</i> por supuesto que el nuevo paradigma nos cambia las reglas del juego humano.

<p><i>¿Qué ocurrió?</i>  Ocurrió que cuando el concepto de realidad cambia desde  lo que es <i>efectivo y tiene valor práctico</i> hasta  la concepción de que  <i>la realidad es el propio cambio en forma de ciclos que se extienden irreversiblemente desde el concepto al uso y regreso al concepto original, modificando la relación en el espacio y el tiempo</i>, resulta fácil  creer,  que todos los procesos son como los percibimos, y así desconocer la verdadera epistemología del Espacio/Tiempo. Pero cada ciclo ocurre también, y no puede ser de otra manera, con una velocidad y una frecuencia dadas. Nosotros mismos, como seres reales, hacemos un cambio continuo en ciclos y frecuencias, la mayor parte de las cuales ya son conocidas y fáciles de detectar. Además, <b>somos y estamos</b> en el espacio y en el tiempo.  <b>Somos  y constituimos</b>  toda la realidad con su <i>velocidad</i>.  No nos debe extrañar, entonces, que el cambio en la realidad compleja también pueda ser detectado, medido, interpretado y controlado. Por eso la DIMENSION CUALITATIVA, es la que cuantifica  y le da  dimensión a la realidad humana.  

<p>Este método, o mejor dicho, esta metódica, que además es un <i>Sistema</i>, permite instalar sistemas inteligentes, capaces de detectar las vertientes, las variables, a la velocidad del cambio de la realidad respectiva,  y por lo tanto permite controlar, evaluar y hacer el seguimiento de todos los procesos, con la condición de que se tenga un marco de referencia de lugar, fecha/hora para los objetivos y metas que se desean controlar, y se dimensione con ellos los flujos de información y energía útiles y éticos al complejo entorno que nos rodea.

<p>Hoy no existen formas, que sepamos, de relacionar los sistemas complejos de gobierno, economía, sociedad, inteligencia, etc. Todos ellos están instalados de manera inercial, empírica y groseramente egocéntrica, o sea, sin tomar en cuenta los veloces y cada vez más acelerados cambios de conductas, que son interactivos con las circunstancias, y que no mejoran oportunamente la calidad de vida, puesto que no saben como hacerlo. No entienden la trascendencia de lo que ocurre hoy y aquí, en relación con lo que sucede más allá y mañana. Confunden el ser, el estar y la dinámica del cambio que los interrelaciona. El resultado no se deja esperar: Cada vez estamos peor.

<p>El gran problema que tenemos es humano, pero especialmente con los líderes y con el criterio científico,  ausente de lo que significa la Dimensión Cualitativa, <i>La Nueva Ciencia, La Pentadimensionalidad</i>, y en síntesis: <i>la realidad</i>.  Es el cambio radical de paradigma que obstruye la comprensión de muchos, sobre todo la de  los que reciben el impacto de haber dedicado grandes esfuerzos y mucho tiempo, a una falsa concepción de la ciencia que nos sumió también en un falso paradigma.  En ese <i>status</i> se encuentran gran cantidad de filósofos y científicos, políticos que detentan el poder y personajes que manejan inmensos intereses económico-financieros; todos ellos  sufren y seguirán sufriendo, paulatina e inexorablemente, la visión de una agonía gradual, proveniente de una forma que necesita vivir en una dimensión socio-política y socio-económica, que se deteriora gradualmente y que no saben como enfrentarla. Las personas sucumben al vértigo del cambio sin darse cuenta de que forman parte de él; los pueblos se agotan y adquieren insospechadas formas de enfermedad y violencia; los imperios se desvanecen poco a poco, el clima se perturba y la civilización se corrompe...El cambio <i>está fuera de control...</i> nadie lo entiende y nadie lo aprovecha, pero él seguirá allí, esperando o destruyendo.

<p>Pero la Nueva Ciencia, por  necesidad y urgencia,  esboza esta forma dinámica e integrada de mantener el ritmo del cambio, tal como es la realidad en  la que está el mundo  del tercer milenio, para despertar una verdadera esperanza, y una vía segura e insoslayable para extender la información y la inteligencia social de los pueblos, dirigiéndola  a los nuevos caminos de una gran redistribución de recursos, sobre todo de conciencia, sobre la forma de subsistir, convivir y sobrevivir.  Si bien esta no es una solución  inmediata, es indispensable, todos los días, profundizarla, y así se hará más y más evidente y consolidada. Abreviando, podríamos decir: <i>“Inteligencia es cambiar con el cambio, sin alterar fines”</i>.

<p>No se está trabajando con lo mejor del hombre ni del patrimonio cultural o material de los pueblos, porque nos hemos enrutinado conceptualmente sobre los viejos paradigmas y  criterios del desarrollo, en detrimento de la verdadera calidad de la vida. La noción de potencial no aparece sino en los motores a gasolina o en las turbinas. Se desconoce completamente el potencial <i>sinérgico</i> y el potencial <i>sintérgico</i> de la humanidad, sencillamente porque no se sabe manejar  la interactivación de las relaciones de culturización, producción, autogestión, cogestión, etc. No se pudo, porque no se supo, interpretar la dimensión humana  que nos abre para siempre a nuestra propia cualidad humana.  No se pudo tampoco interpretar la relación entre <i>dimensión y cualidad</i>. Ignorábamos que nos movemos en un mínimo de cinco dimensiones, en las cuales la última integra existencialmente las otras cuatro. 

<p>No se tiene idea de lo que es la <i>Sistematización de la Inteligencia</i>. Mejor dicho, no se sabe ni siquiera qué es <i>Inteligencia Social</i>, ni las técnicas para instalar los sistemas inteligentes. Miles de científicos e investigadores, la mayoría de <i>buena fe</i>, trabajan en profundizar la especificidad de cada variable, pero no saben interactivar la matriz de sus vertientes universales, ni tampoco codificar e interactivar los macrosectores de la interdisciplinariedad universal.

<p>Por coincidencia o persistencia, hemos logrado  profundizar la generalidad de las perspectivas de la ciencia a la velocidad del cambio, con el objeto de establecer las pautas existenciales a todo proceso investigativo, docente y extensivo (como deberían hacer nuestras universidades).
 
<p>Resulta conveniente, para los estudiosos y líderes del actual <i>status</i> de la humanidad, comprender, interpretar nuevas acciones concurrentes y focalizar el nuevo paradigma, cosa por demás sencilla, que surge de la novación y redefinición del concepto de <i>Realidad</i> como proceso y flujo de cambio continuo. No hay que llegar al abstracto complejo, sino al estudio del concreto <i>real</i> de la Dimensión Cualitativa para mejorar nuestra apreciación general sobre el significado de la vida y su verdad en movimiento trascendente.

<p>Para dar un paso hacia adelante en este esfuerzo para sincerar la filosofía, las ciencias actuales, la política, la economía, etc., tendremos que regresar, aún cuando sea sucintamente, a dos fundamentos previos a la Dimensión Cualitativa: la <i><a href="#" onMouseOver="stm(Text[3],Style[1])" onMouseOut="htm()" class=tip2>Filosofía Integralista</a></i> y la <i><a href="#" onMouseOver="stm(Text[4],Style[1])" onMouseOut="htm()" class=tip2>Teoría del Conocimiento Trialéctico.</a></i> Luego veremos sus tres funciones trascendentes. Una estrategia para el desarrollo social seguida de una concepción de la geo-historia como fuente de los sistemas inteligentes en general, que causan desde los criterios de la nueva ciencia y su paradigma la sistemática que maneja la relación científica (la interactivación de la ciencia con la realidad de su cambio.)

<p>Veremos luego en la segunda parte, (tercer Capítulo)  con un poco más de detalle, la realidad, la interdisciplinariedad y luego en el Capítulo IV un  ejemplo de tecnología transdisciplinaria, como es el Catastro Integral y sus colaterales digitalizados para cubrir áreas del desarrollo social, derivando  hacia un tema convencional que surge como aplicación directa, para terminar en una conclusión como componente  de una filosofía vital.

<p>En la Segunda Parte de este documento, nos ocuparemos de la Plataforma Conceptual y los Sistemas inteligentes que llegan hasta la propia fórmula  pentadimensional de la Dimensión Cualitativa, para luego mostrar su   práctica al campo social, político y  económico. 

<p>Estos sistemas, que son un resumen de instrumentos que han surgido de los estudios sistemáticos e interdisciplinarios,  desde los cuales se ha podido, poco a poco, dilucidar diferentes formulaciones metodológicas, han permitido lentamente, en casi medio siglo, escudriñar,  no por casualidad sino por sistema, el mismo concepto ya enunciado  de <i>realidad como proceso de cambio continuo</i>. Su praxis  nace también del  <i>Sistema de Sistemas</i>, a velocidad de diseño inteligente y para beneficio de la redistribución a favor de los pueblos del mundo.

<p>Por último, ya al final, entraremos rápidamente al primer  ejemplo, con mucha actualidad en la geopolítica del planeta concreto, con un modelo metodológico de Municipio Inteligente, que se transfiere expansivamente a Región Inteligente, País Inteligente, Corporación Inteligente, etc, etc. Sabemos, a ciencia cierta, que las instituciones político-administrativas, de corte centralista y con tendencia a la concentración de recursos políticos y  económicos ya entraron en franca decadencia, y deben ser renovadas con propuestas acordes a los tiempos que vivimos. Tiempos de Inteligencia Social.

<p>La razón es muy sencilla: el costo del esfuerzo realizado para centralizar y concentrar, ya no resiste mucho más la desproporción del crecimiento y la velocidad  de la universalización y capacidad energética de control remoto. Es algo así como colocar un motor de cuatro pistones a cien mil revoluciones por minuto. Este gran proceso se está globalizando con matices autárquicos innegables y acelerados. Así podremos observar, con toda claridad, como se llegó al MAPA SOCIAL y como muy pronto podremos apreciar y ejecutar Sistemas Autonómicos. 
 
<p>Al culminar este planteamiento  y su respectivo documento en forma de texto preliminar, tratando de ser contundentes, se culminará también con la etapa del proyecto extensivo a nivel tecnológico de sistemas e instructivos básicos, para que cualquiera que tenga real interés pueda interpretar y por lo menos establecer criterios generales de actuaciones concretas en su área profesional y social. El eslabón entre la investigación mencionada (investigación extensiva) y la extensión social es la genuina praxis del Municipio y los demás órdenes sociales inteligentes.
	
<p>Quizás podría criticarse la combinación de un texto de alto  nivel conceptual, como es la Dimensión Cualitativa o la Pentadimensionalidad,  el cambio necesario de un nuevo paradigma para la ciencia, con un ejemplo o modelo de aplicación netamente pragmático. 

<p>La crítica podría ser válida si no fuera porque la única manera posible de hacer verdaderas investigaciones y llegar a conclusiones  concretas , es <i>abriendo la realidad</i>, como proceso de transferencia, de cambios y de integraciones teórico-prácticas, relacionadas en el espacio tiempo con los objetivos y metas que se persiguen. ¿Sabía usted que la <i>realidad se abre</i>, como se abre en informática un archivo con un <i>clic</i>?.  Sin embargo, ese <i>abrir</i> sucede en la mente y en la intención, y no en el computador. Al estudiar el <i>Municipio Inteligente</i>, usted entenderá  cómo se abre un municipio. Así se abre cualquier instancia personal, familiar, institucional, social, nacional o planetaria.

<div class=menu><table width=100% border=0><tr><td align=left width=33%>&nbsp;</td>
	<td align=center width=33%><a href=index.html>Indice</a></td>
	<td align=right WIDTH=33%><a href="filosofia.php">Filosofía Integralista</a></td></tr></table></div></div>

</body>

</html>
