<!doctype html public "-//w3c//dtd html 3.2//en">

<html>

<head>
<title>Dimensión Cualitativa - Parte 5</title>
<link rel="stylesheet" type="text/css" href="estilo.css">
<SCRIPT language="JavaScript1.2" src="../../js/main15.js" type="text/javascript""></SCRIPT>
</head>

<body>

<DIV id="TIP" style="visibility:hidden;position:absolute;z-index:1000;top:-100;"></DIV>
<SCRIPT language="JavaScript1.2" type="text/javascript" src="introduccion.js" ></SCRIPT>

<div class="subtit" style="position:absolute;top:2px;">
La Dimensión Cualitativa
</div><br><br>

<div id="cuerpo" style="width:570px;">

<h2>PARTE V: LA FUNCION PROFUNDIDAD</h2>

<p>Todo en la vida, de alguna manera, trasciende. Los  primeros que trascendemos somos nosotros. Efectivamente, somos criaturas que comenzamos a ser con nuestros ancestros, generando familias que se van multiplicando hacia el futuro. Nadie podría decirnos exactamente cuándo fue constituido el primero de los genes que hoy nos conforman. Tampoco nadie nos puede decir cuál será el final del último gen que provenga de nosotros, en el último de nuestros descendientes.

<p>Todo eso ocurre en una trayectoria vital llamada vida: el presente, con su pasado y su futuro. Todo ocurrió, ocurre y ocurrirá en las dimensiones del espacio y el tiempo, y en ellas, transcurrimos nosotros, nuestros aprendizajes, conocimientos, acciones y nuestros procesos en general.

<p>Pero lo importante no es lo que ocurre, sino la respuesta que encontramos a lo que decimos, hacemos y proyectamos. Si hacemos muchas cosas buenas, lo lógico sería que encontremos la respuesta estando aún vivos. Si nos llegara después de muertos,  no seríamos unos actores profundos y eficientes ya que dichos resultados  <i>post mortem</i>  no pueden ser evaluados en esa otra  dimensión constituida por un pasado no renovable.

<p>En tal virtud, la profundidad no es sólo una magnitud, como dimensión que es; también es un concepto trascendente y potencialmente infinito, y se integra con otras funciones a lo largo de ese eje o trayectoria del <b>ser</b> individual, traducido en desarrollo familiar, comunal, etc. Veamos unos ejemplos:

<ol>
<li>Si hago nado submarino  no tendría que explicárseme qué es   profundidad física en el  mar, ya que percibimos directamente la respuesta de sus efectos. 
<li>Si lanzo una piedra en la corteza terrestre, la piedra caerá por gravedad, pero si la lanzo desde una plataforma a 400 kilómetros de la superficie, es posible que la piedra no llegue nunca, y hasta podría ocurrir que girara continuamente en el universo sideral. No obtendría respuesta. Aquí estaríamos en presencia de un concepto de profundidad  negada de las ciencias fácticas. 
<li>Si un General en plena guerra, da una orden a sus subalternos y no llega a saber si fue o no cumplida, ese ejército seguramente  perderá la guerra, por que no se obtuvo respuestas oportunas. No hubo profundidad militar. Aquí estaremos en presencia de una profundidad  negada de efectividad, eficacia y eficiencia.
</ol>

<p>En los tres casos, hay algo que tiene sentido de <i>profundidad</i>, cuando, por ejemplo, emitiendo una información o ejerciendo una acción concreta, se obtiene <b>una respuesta útil, completa  y oportuna (UCO)</b>. Sólo así, pueden permitirse cambiar las circunstancias que se mueven en el propio suceso y en dirección y sentido al objetivo propuesto. Lo <i>útil</i> tiene que ver con la pertinencia de nuestros objetivos y de la vida; <i>lo completo</i> con el ser y estar en el espacio-tiempo,  y <i>lo oportuno</i> con la velocidad y la aceleración de nuestros potenciales al  introducir información e inteligencia en el tiempo ( sinergia) y manejar la energía en todas sus formas dentro del espacio respectivo, con conciencia de hacerlo (sintergia).   

<p>La <i>profundidad</i>, resumiendo, es una coincidencia de movimiento sobre un eje imaginario de conceptos y/o acciones en los que se recibe respuesta oportuna. La causa coincide o no con el efecto buscado  o natural, gozando   tal  movimiento de las características propias a todo lo que se mueve, respira, vibra, ondula, oscila, etcétera. Una ocurrencia en el  espacio-tiempo, con o sin resultados. Digamos entonces, en un sentido un tanto geométrico, que la <i>profundidad</i> es <i>longitudinal</i> al eje espacio-tiempo, en coincidencia con el de  causa-efecto.

<p>Si quisiéramos representar la función <i>profundidad</i>, con una analogía lógico-matemática, la  dibujaríamos así:

<p>Al expresar <i>conceptos básicos</i> sobre la profundidad de los procesos, nos damos cuenta de que, si todo lo que existe se mueve, entonces la profundidad de un movimiento cualquiera está dada por esa coincidencia posible entre el objetivo que quiere convertirse en resultado, sobre un eje Z y Z´, en el que las tres dimensiones del espacio coinciden con el transcurso del tiempo, y se obtiene <i><b>respuesta oportuna</b></i>.

<p>Sintetizando, diríamos: la profundidad es proporcional a la respuesta oportuna. Ahondemos un poco más. 

<ul>
<li>En un matrimonio posible, el futuro marido hace una proposición, pero la novia no tiene respuesta útil, completa ni oportuna: útil en cuanto que no define la respuesta a la propuesta. No hay  referencia en cuanto a que no existan condicionamientos ni oportunidad, en el momento de la propuesta. 
<li>La oferta en el remate de un inmueble tiene que ir acompañada de la entrega material (bolívares) por el monto acordado por el bien rematado, y en dinero efectivo o bien certificado. Diríamos entonces que esas dos respuestas constituyen una función profunda. El <i>objetivo</i> se convierte en resultado en el espacio y en el tiempo real, o por lo menos oportuno.
</ul>

<p>La <i>profundidad</i> es una función pentadimensional, que a su vez, tiene conexión existencial con los procesos de ingreso, tanto de información como de acción y producción, o sea de energía, expresada en todas sus fórmulas físicas y mentales. Esa información y esa energía coadyuvan o no a la profundidad, porque su sentido,  ya no solamente del proceso particular, sino del sistema universal, se acumulan progresivamente.  El proceso <i>universal</i> se moviliza al tenor de las micro decisiones de todos y cada uno de los hombres, en cada sitio y momento en que ocurren.  Exagerando... y para resaltar el ejemplo, diríamos: Cuando una persona arroja saliva  en el piso, se contamina el universo.

<p>Esto sucede cada vez que el hombre, al consustanciarse con su fuente originaria y total de ser y estar en algo, siente que  su vida se acrecienta en su estado  consciente,  al encontrarse  también con que su entorno lo vincula con sus querencias, y cada vez más, con sus objetivos y metas.  El ha encontrado la manera práctica de ascender. Esta función de ascenso, que bien podría ser de signo contrario, o descenso, en la que ese hombre hace coincidir o no su eje de espacio-tiempo con sus objetivos, y  convierte estos en resultados, con su conocimiento y su trabajo,  aportando conscientemente sus facultades, en general  es sinónimo de <i><b>profundidad</b></i>.  

<p>Cabe acotar que esa profundidad no es longitudinalmente en un solo eje y sentido. Cuando practicamos el nado submarino, tratamos de profundizarlo y encontramos una resistencia, tanto en la creciente densidad de la presión que recibimos, debida  a la columna de agua, como por nuestra falta de oxígeno, cada vez mayor a más profundidad. La profundidad tiene entonces sentido positivo,  sentido negativo y una relación de encuentro de lo que sería aquel momento en que lo positivo se encuentra con el regreso, en forma de respuesta. La misma puede cambiar de signo de la actividad, pero también puede cambiar el de la función, el proceso o todo el sistema. 

<p>Cuando lanzamos la piedra verticalmente hacia arriba, encontramos que a nuestro esfuerzo se opone la fuerza de la gravedad y además, la resistencia del aire y nuestro impulso, limitado a la capacidad muscular para lanzarla.

<p>Cuando el General ordena al Coronel tomar un cerro inmediatamente que el mismo sea bombardeado, si no encuentra la respuesta cuando ya eso se efectuó, queda impedido de dar la orden de <i>toma</i>. ¿Quién será el responsable por la omisión? Además de la desinformación sobre la acción del Coronel, se le ha colocado en el nivel de incertidumbre total. ¿Qué hacer entonces?. Hay una sola respuesta: seguir el sentido y dirección del objetivo. Vale más una equivocación que la incertidumbre de la verdad desconocida para siempre. La primera tiene aprendizaje, ajuste, seguimiento... la segunda consume gradualmente el proceso total. 

<p>Ese movimiento longitudinal, en el eje del espacio-tiempo, de carácter tetradimensional, teleológico, con sentido y dirección de objetivos y metas, es perpendicular, por decirlo así, a un entorno en el cual existen campos complejos de energía e información, en los que se reciben efectos recíprocos positivos y negativos a dicho movimiento y también de otros campos más distantes, de los cuales  no llegan  efectos perceptibles, lo que no quiere decir que no existan. La percepción de la información veraz es la aliada de la decisión. Por esa razón, tenemos que valorizar el <i>tiempo real</i>. Tenemos que hacerlo con el espacio-tiempo real. Tenemos que privilegiarlo con la <i>información real</i>; tenemos que aprovechar siempre la oportunidad de hacerlo con la <i>energía real</i>, sobre el sentido y dirección del objetivo. Ese es, justamente irreversible, incontrastable, insoslayable y definitivamente, el verdadero contenido teleológico de <b>la realidad</b>.

<p><b>LA MEJOR PROFUNDIDAD ES LA PROPIA REALIDAD.<br>
EN ELLA SIEMPRE HAY RESPUESTA OPORTUNA Y MUY EFICIENTE.</b>

<p>A tal efecto vale la pena añadir que el ser humano percibe, siendo optimistas, sólo un 0.0003 por diez trillones del espectro universal, en el que él es protagonista.  Ve, oye, gusta, huele, toca, y en esa proporción, sus receptores trasmiten sólo una pequeñísima parte al cerebro. Pero esa pequeña proporción sensible, se convierte en una infinita capacidad conceptual, cuando ese mismo ser, sabe,  interpreta y prospecta su <i>ser y su estar</i> en función y relación a los valores universales.  Su captación de frecuencias ondulatorias y corpusculares es casi nula. Hay otros animales que centuplican su capacidad perceptiva y ondulatoria. Hay tecnologías que la aumentan miles y ahora millones de veces. Desde allí, desde  esa profundidad, que no es sólo corpuscular y ondulatoria, sino también intuitiva y que  toca los límites de la espiritualidad, es donde nace el verdadero sentido de esa unidad simbiótica del ser humano con el universo, como lo veremos más adelante: el concepto básico y su presencia compleja pertinente y persistente hacia objetivos trascendentes. 

<p>Esos efectos dependen  de la calidad y cantidad de la onda que constituye la fuente del impulso. En Nagasaki e Hiroshima, después de cincuenta y siete  años, todavía mueren personas por causa indirecta de las primeras explosiones nucleares; en los tribunales de Primera Instancia en lo Civil y Mercantil de la ciudad de Caracas, Venezuela, todavía se sienten los preceptos jurídicos de las instituciones de Justiniano, del tiempo de los romanos, y se respira aún la profundidad filosófica de un Sócrates y un Aristóteles.
 
<p>La función trascendente <i>Profundidad</i> es coexistencial a las funciones de <i>Intensidad y Velocidad</i>. Cabe señalar que si bien hemos manifestado la relevancia de dicha función en el sentido teleológico longitudinal, es también en estas otras funciones donde  quedan sobresalientemente reflejados  los procesos energético-informativos y los del espacio-tiempo. Todos ellos suceden sobre la proyección de ese eje virtual de espacio-tiempo en el que se define o no la coincidencia con los fines humanos .

<p>Observamos en la figura siguiente un esquema elemental de <i>Profundidad en cinco niveles</i>, planteado sobre una matriz aritmética cuya escala longitudinal va desde 0 hasta 5, y transversalmente tenemos en ambos sentidos, a derecha y a izquierda, una simulación de secuencia en los Pasos Metodológicos* desde el ASH (Análisis Sistemático-Histórico), pasando por II (Inventario Inercial), ID (Inventario Dinámico), P1 (Visión o Perspectiva),  P2 (Proyectiva), P3 (Prospectiva), 0 (Operativa) y S (Secuencia). Pasos Metodológicos que asoman valores aritméticos de resistencia y eficiencia por y para el cambio en un entorno dado.

<p>Estos Pasos Metodológicos, transversalmente ubicados, significan un entorno que diluye el esfuerzo, ya que la profundidad es neutralizada por la resistencia directa al esfuerzo. Mientras más lejano es el efecto colateral que interfiere, más débil es la profundidad. Desde allí se infiere que cada decisión inteligente debe contar, como ocurre en un juego de ajedrez, con un análisis de la situación.  Ser inteligente equivale siempre  a realizar labores de prevención, que bien podríamos catalogarlas como de contrainteligencia. Sólo las decisiones profundas, previsivas y reiterativas sobre un mismo objetivo, llegan a tener éxito. Todos los procesos y sistemas inteligentes están fundamentados en la facultad para prevenir y planificar estratégicamente, tomando en cuenta los vectores y fuerzas adversas, y por lo tanto, instalando sistemas de prospección.

<p>Generalmente el primer impulso decisorio  es el más importante porque constituye la ruptura de la rutina o la inercia. La primera vuelta que da la rueda de un vehículo es indudablemente la más lenta, pero al mismo tiempo equivale al mayor gasto energético, ya que el carburador debe estar tan lleno como sea necesario, para que la primera chispa mueva los émbolos o pistones y éstos a su vez trabajen, con el cigüeñal, las vueltas que dará la rueda sobre el pavimento. A su vez la velocidad del vehículo dependerá del número de vueltas que genere el recorrido, etc. Aquí es donde sobreviene lo más importante de la función <i>profundidad</i>. La respuesta negativa, la contrainteligencia y las fuerzas   inerciales  del   entorno,  que  por   serlo neutralizan el esfuerzo inicial, deben ser oportunamente reforzadas por un nuevo e imperativo impulso, también inteligente en su nueva oportunidad, antes de que fallezca el primero. De lo contrario habría que comenzar de nuevo, y eso representa mucho más consumo de energía e información. Hay un proverbio popular entre los jugadores de dominó: <i>“El que no repite no gana.”</i>

<p>Si en el nado submarino mis brazadas no son secuenciales, moriré ahogado; si lanzo la piedra verticalmente y no me quito, el retorno de la piedra me podría, inclusive, matar. Si el general no recibe respuesta de su coronel, posiblemente el enemigo terminará haciéndolo rendir y apresándolo. Todo lo que no es pertinente y persistente tiende al fracaso y a la muerte anticipada. Los matrimonios se deshacen y los partidos de ajedrez se pierden por falta de claridad de objetivos y por falta de inteligencia pro-activa, o por desconocimiento de los factores inerciales o de  la contrainteligencia del opositor.

<p>La vida y toda la realidad se mueve en frecuencias, secuencias dirigidas,  y presencias teleológicas (pertinentes al esfuerzo inicial). 

<p>La <i>profundidad</i>  no es un hecho aislado, sino un gran sistema de equilibrio y armonía en la que <i>todo lo que entra no sale</i> igual,  y <i>todo lo que sale no entra nuevamente</i>, igual. Esto se debe a que siempre hay un cambio presente en los procesos; el movimiento tiene la categoría de ese cambio. Hasta la propia verdad en movimiento tiene su respectivo valor de cambio y también tiene desgaste. Todo cambio es elemento existencial  de toda realidad. La realidad es existencial al cambio y con él a la compensación universal, a la ley de la optimización* y a todas las leyes y procesos que funcionan con variables dependientes e independientes. Todos esos cambios son derivadas veloces que generan otras derivadas acelerables hasta llegar, bien a la nanotecnología, bien al fractal, bien a la flor de la recursividad, bien a las matemáticas no lineales, bien a la topología social o a la arquitectura conceptual y a la ingeniería social. Pero cada derivada tiene relación con una integral: la integral de quinto, sexto o séptimo orden que es la realidad, ha pasado por cinco, seis o siete  derivaciones sucesivas. Por eso es importante la suma, en relación con la resta, pero aún más lo es la multiplicación en relación con   la división, y mucho más la derivada en relación con la integral de primer orden,  y aún mucho más importante es la relación entre cada ser humano y el universo ( integral de N órdenes).    

<p>“La realidad es un proceso de cambio continuo y acelerado de flujos de energía e información en el espacio tiempo, con causa y efecto”. 

<p>La <i>profundidad</i> es eminentemente específica y su sentido y dirección no excluyen cierto desgaste que alimenta a gestiones  de otros procesos. <i>Si obtenemos respuestas útiles, completas y oportunas a nuestros conceptos y a nuestras acciones dirigidas, somos profundos</i>. El hombre que muere deja su sangre, su apellido  y su tradición a los hijos; el árbol que muere sirve de abono para nuevos árboles; la guerra que se pierde deja la transculturización del vencedor y el significado de la paz en el vencido; la mejor vacuna es la de la fuente de la enfermedad, o sea, la información genética molecular de la propia enfermedad, debilitada, que permite crear los anticuerpos inmunológicos.

<p>La función <i>Profundidad</i> podemos asimilarla al concepto de jurisdiccionalidad,  en el sentido de que normatiza para una finalidad dada,  un conjunto de preceptos y sanciones para un régimen taxativo, en el que se trata de lograr una conducta constructiva  y se repele una anticonducta destructiva. La historia de las leyes y la filosofía del derecho, así como la sociología jurídica, no son otra cosa que fuentes profundas de generación cognitiva. 

<p>Las leyes no nacen como preceptos. Nacen de un equilibrio, armonía y valoración innatas en el propio saber, querer y deber inmanentes en cada ser humano. Así se convierten en  geo-historia las informaciones que pasan de la percepción a su mente relacionadora. Esa mente encuentra en el entorno cognitivo del universo la forma de hacer funcionar sus propios órganos, con  sus  procesos bio-fisio-eco-psico-socio-político-valorativos y económicos que van a dar irreversiblemente a la infraestructura de la naturaleza, bien para mejorarla o dañarla, regresando a lo que aparentemente es su mismo ciclo. Pero no existen dos ciclos iguales, y es así como los órdenes conceptuales hacen nacer e incrementar valores de permanencia institucional y se generan deontológicamente como preceptos y valores éticos las  normas constitucionales, leyes orgánicas, leyes ordinarias, decretos leyes, resoluciones, ordenanzas, reglamentos y procedimientos en general. 

<p>La función <i>profundidad</i>, coincidente entre el espacio-tiempo y la etioteleología hace que su eje sea la columna vertebral del universo. Sobre ella giran el hombre y todas las civilizaciones; todo el escenario cósmico se estremece cuando un hombre degrada su identidad o la identidad de sus relaciones con la naturaleza, porque todo él sufre la contaminación destructiva que se encuentra en la ignorancia y en la falta de cultura. 

<p>Está claro que la <i>profundidad</i> es existencial, como ya lo dijimos, a las otras funciones trascendentes, para seguir relacionando y ascendiendo funciones de <i>intensidad y velocidad</i>, y ninguna de las tres  existe separada. Como tampoco existe sólo el espacio-tiempo sin la energía-información ni la causa-efecto. Estos principios de Filosofía Integralista nacen con el universo e irán desapareciendo con su propia involución.

<p>Cuando hablamos de funciones trascendentes estamos existencialmente afirmando,  que la esencia  del <i><b>onto</b></i> es su teleología en el espacio-tiempo, pero es existencial de manera absoluta al poder trascendente que ejerce el <i><b>Dominus</b></i> (saber, conocimiento, conciencia, inteligencia) y a la inmanencia del <i><b>Corpus</b></i> (cuerpo de acciones por necesidad, por experiencia, por producción de insumos vitales y materiales). Son las funciones que permiten, no sólo conocerse a sí mismo, sino leer la realidad del entorno, convivir con la capacidad de ser necesarios y necesitar más capacidad para sobrevivir mejor; ampliar el saber para tener más poder y utilizar éste para poseer el don trascendente de saber dar y enseñar.

<p>Queremos acotar que la <i>profundidad</i>, por ser enunciativa y  relevantemente longitudinal, tiene mucho que ver con la altura desde la cual se realizan las perspectivas humanas.

<p>No es lo mismo una perspectiva o visión desde la altura del nivel natural del ojo, que la que obtenemos desde la azotea de un rascacielos o de un avión. Tampoco podemos ver, al natural, los mismos detalles de nuestro piso, cuando caminamos en él o cuando observamos un mismo objeto desde varias alturas. Es decir, que cada profundidad es preventivamente analizada por una visión o perspectiva que le es proporcional. Cada resultado obtenido es también la consolidación de una personalidad profunda que sugiere un aumento de la visión experimentada y del estado de conciencia y responsabilidad personal.

<p>No estamos diciendo nada que el lector no  sepa, o por lo menos, intuya. Pero la importancia de decirlo no consiste en denotar la existencia de esos fenómenos y subsiguientes procesos, sino que los mismos, además de aplicarse al sujeto conocedor de los objetos de su conocimiento, se aplica a todos los objetos cognoscibles por cualquier sujeto que conozca.  Lo que tiene valor objetivo es la relación de un verdadero conocimiento, a lo largo de sistemas de información inteligentes, profundos y por lo tanto eficaces y eficientes.

<div class=menu><table width=100% border=0><tr><td align=left width=33%><a href="funciones.php">Funciones Trascendentes</a></td>
	<td align=center width=33%><a href=index.html>Indice</a></td>
	<td align=right WIDTH=33%><a href="intensidad.php">Función Intensidad</a></td></tr></table></div></body>

</html>
