<!doctype html public "-//w3c//dtd html 3.2//en">

<html>

<head>
<title>Dimensión Cualitativa - Parte 7</title>
<link rel="stylesheet" type="text/css" href="estilo.css">
<SCRIPT language="JavaScript1.2" src="../../js/main15.js" type="text/javascript""></SCRIPT>
</head>

<body>

<DIV id="TIP" style="visibility:hidden;position:absolute;z-index:1000;top:-100;"></DIV>
<SCRIPT language="JavaScript1.2" type="text/javascript" src="introduccion.js" ></SCRIPT>

<div class="subtit" style="position:absolute;top:2px;">
La Dimensión Cualitativa
</div><br><br>

<div id="cuerpo" style="width:570px;">

<h2>PARTE VII: LA FUNCION VELOCIDAD</h2>

<p>La tercera función trascendente, la <i>Velocidad</i>, complementa la pentadimension en la <i>Dimensión Cualitativa.</i> La  velocidad es inmanente e inherente al ser, cualquiera que sea su orden o nivel de complejidad. Está claro que la complejidad es directamente proporcional al movimiento  y que en el orden humano se alcanzan las complejidades propias de altísimas velocidades, pero, que no obstante, nunca ese ser ha quedado conforme con las máximas velocidades de su era o de su época... siempre quiere más.

<p>El hombre nadaba, se arrastraba como reptil y luego caminaba en cuatro patas cuando todavía no había aprendido a mirar el horizonte. Luego, al erguirse y mirar las estrellas, intuyó nuevos valores y con la tracción de sangre, luego con la rueda y después con distintos mecanismos de propulsión, llegó a vencer la gravedad del suelo y  levantarse hacia un mundo todavía más complejo, a grandes velocidades. Luego, no sólo venció la gravedad de su suelo sino la del planeta completo y se elevó aún más para explorar otros mundos. Cuando alcance esos mundos, entonces tendrá que regresar a la conciencia de universalidad, en la que él  es el protagonista que homologa su propia búsqueda. Pero podría ser tarde para regresar.

<p>En este tercer milenio, estamos buscando más velocidad y complejidad.  Trataremos de  trasmutarnos electrónicamente para llegar a los confines del universo. Será, si lo logramos, a velocidades como las de la luz  y las del  lumínico... ¿Estaremos entonces contentos? 

<p>Pero ello no es tan relevante como el ascenso que pueda lograr con la comprensión de las grandes causas que le han ocultado su verdadera pertenencia al cosmos, del cual viene y hacia el cual se mueve incesantemente. Cuando el hombre cree en Dios y se mueve hacia el infinito, con la filosofía, con todas las ciencias sin excepción: matemáticas, física, biología, geografía, astronomía, filosofía, religión, etcétera, lo único que confirma y conforma es su propia naturaleza <i>real</i>. El siempre quiere saber lo que pasa, dónde  pasa y en el propio sitio donde pasa; si  es posible, dominar todos los caminos de esa información real, en espacio real, en tiempo real y con la energía de sus propias fuentes. Pero no quiere hacerlo a cualquier velocidad, porque al pretender condiciones <i>reales</i>  lo que quiere es la máxima velocidad posible... Repetimos: el hombre está en, y es, espacio–tiempo; también es y está en las relaciones de espacio/tiempo... el hombre es velocidad. O sea: lo que vale del hombre no es saberse veloz, sino saberse <i>cambiante</i>, pero con destino perfectible. 

<p><b>Corolario:</b> Lo que vale del hombre es su conciencia universal y poder de ascenso con la poderosa mente que le ha generado el universo, hacia la comprensión y realización plena de su ser. Pareciera que estas argumentaciones son exageradas, pero ocurre también que están totalmente confirmadas en los miles de procesos de la geo-historia, en todos los lugares y circunstancias. En efecto, recordemos que el sentido analógico matemático de la profundidad,  se orienta relevantemente en el aspecto longitudinal, motivo por el cual  puede dársele connotación jurisdiccional. Pues bien, en la filosofía del derecho, en la sociología jurídica y en la jurimetría , se prueban los impulsos eternos del ser humano en la búsqueda de la optimización del espacio y el tiempo.  

<p>Por otra parte, cabe relacionar que,  si bien la <i>Intensidad</i> llena el aspecto transversal, cíclico, justificando la interactividad interdisciplinaria e intersectorial que se observa en el gráfico correspondiente, la velocidad cumple con la tarea de relacionar la profundidad longitudinal y la intensidad transversal. Esto equivale a asegurar la homologación, las analogías y la isometría conceptual entre la realidad como cambio continuo y la Dimensión Cualitativa con la integración de sus tres funciones trascendentes.

<p>Recordemos  que el <i>quid</i> de la realidad, como proceso de cambio continuo en el que participamos todos los entes en general, situados en eso que llamamos <i>El Universo</i>, especialmente los más complejos, direccionados y trascendentes que somos los seres humanos, es el continuo cambio relacional de la pentadimensionalidad.

<p>Pensemos que ese cambio puede tener velocidad uniforme, puede ser de velocidad alternada o, puede ser como en realidad  es, de velocidad creciente.

<p>Respecto a eso, cabe afirmar que si bien el tiempo no es renovable, en cambio la información y la inteligencia que  de el puede surgir  sí lo son, y es el incremento sistemático de la información la que produce la apertura del ángulo que abre y acumula la inteligencia humana. Es por esta razón que la figura del gran sistema de la Dimensión Cualitativa coincide con el esquema de la Plataforma Conceptual de la <b>página xx</b>  y está constituida fundamentalmente por un conoide. Aquí se muestra el mismo esquema, pero sólo con  las características de las tres coordenadas cualitativas.
	
<p>En el  gráfico correspondiente podemos observar que la velocidad en la circunvalación de un ciclo, tiene una duración que se mide sobre la escala de tiempo. Pero al mismo tiempo, existe una escala de traslación del móvil que rota proyectada sobre su eje longitudinal de <i>causa a efecto</i>,  o lo que es lo mismo: <i>objetivos en busca de los resultados</i>.

<p>Debemos recordar ahora una fórmula de física elemental donde el espacio sobre el tiempo nos marca la velocidad y la derivada de ésta, o sea, el espacio sobre el tiempo al cuadrado, marca la aceleración. Entonces concluimos que la velocidad del proceso que nos atañe puede ser conocida,  al igual que su aceleración. Además eso nos obliga a reflexionar sobre lo inherente que somos, ya no solamente al espacio y el tiempo sino a la propia velocidad y su aceleración.

<p>Esa es, por supuesto, la velocidad de un ciclo que se extiende desde su concepto básico hacia la utilización en forma de acción del mismo. Luego regresa el móvil, como información útil, <i>con el paso del tornillo</i> al mismo sitio de la curvatura, pero desplazado en el espacio-tiempo y más cercano al logro del objetivo. La velocidad de los ciclos será la equivalente a la frecuencia con que se mueve el proceso y su otra dimensión será la longitud de onda  promedio en dicho intervalo. No estamos diciendo nada nuevo: todo tiene frecuencia, secuencia, longitud de onda, ciclos y mutaciones. Todo tiene valor. Hay una sola cosa a la que el ser humano no le puede dar valor agregado de tiempo: pero sí lo puede hacer aumentando subjetiva y socialmente  sus gestiones de <i>intensidad, profundidad y velocidad</i> dentro de  su propio espacio tiempo, en su propia existencia de perfectibilidad o de ascenso al infinito.

<p>Las tres coordenadas y sus relaciones de cambio , tal y como veremos en “El Municipio Inteligente”, son trascendentes, no sólo por haberse generado en multiformes  analogías lógico-matemáticas sobre el uso del concepto, sino porque hay otras analogías, homologaciones e isomorfismos con la gramática generativa, con la biología molecular y con todas las ciencias aplicadas. La <i>velocidad</i> es una función trascendente que, conjuntamente con la <i>profundidad</i> y la <i>intensidad</i>, nos permiten fracturar la cadena inercial de la ciencia. Esta ciencia que se encontraba ciega a la realidad como proceso de cambio continuo y que no veía tampoco más allá de las cuatro dimensiones (cuando veía mucho). Ella está desapareciendo paulatinamente para dar paso a los ciclos interdisciplinarios del conocimiento investigativo y de la acción extensiva.

<p>Observemos que en la primera alternativa funcional, referente a la  <i>profundidad</i>, a pesar del movimiento sobre el eje, de sentido y dirección conocida, y en la segunda, de velocidad tangencial de la rotación intersectorial, el sistema no se ve afectado por un traslado global del mismo, cuando se va abriendo y al mismo tiempo desplazándose. 

<p>Pues bien, la velocidad es producida desde  el propio movimiento particular y específico de un átomo, una molécula, una célula, un tejido, un órgano y un cuerpo humano, que también denotan la existencia de un universo  y que se causan en el ciclaje y secuencia de esos flujos de información y energía a través del espacio-tiempo.  

<p>Las unidades que denotan esa interacción universal son muchas: el elemento alfa, el concepto, el fractal, la relación, la función, el cambio, la velocidad, la unidad, la totalidad, etc. Es realmente maravilloso que, a pesar de ser varios, todos ellos se unifican en uno solo, que define a cada uno en su propia existencia: el concepto.


<p>Tal como ocurre con nosotros, con nuestros órganos y con nuestro mundo social y nuestro cosmos, todo tiene frecuencia de ciclos y secuencias cognoscibles: ocurre con un electro-cardiograma, un electro-encefalograma, un mio-grama, etc. Así sucede isomórfica y homológicamente con el tejido y los órganos de la sociedad humana en el planeta. Ella denota, siguiendo la analogía, como  un <i>alza de tensión</i>, un desequilibrio eléctrico en la pila que mueve el corazón y que necesitaría un <i>marcapasos</i>; denota, además, una falta de compensación en el oxígeno que circula desde los pulmones y que lleva el precioso carburante al motor de la vida: el corazón de un hombre y el de toda la humanidad viviente. Estamos en una homeóstasis “universal”.

<p>La velocidad o frecuencia vital de todos los órdenes sociales y cósmicos, tiene varias características que se expresan en las analogías lógico-matemáticas representadas por el Conoide, todas  de importancia única, a saber:

<ol>
<li>El aumento de la velocidad tangencial al nacimiento de todo ser, es notorio en los primeros ciclos de la vida; en la primera sección conoidal, individual o colectiva, que surge como incremento fundamental de los procesos de desarrollo inicial. En esta etapa el recorrido implica más trabajo de crecimiento cuantitativo en el espacio-tiempo y la preparación de una estructura continentalizada, para soportar cargas energético-informativas mayores que se suceden cuando llega la madurez de la vida.

<li>La disminución de la velocidad tangencial, porque al incrementarse los ciclos  e ir agrandándose su larga órbita, todo el movimiento del sistema pone acento intermedio entre el transcurso del espacio-tiempo y los flujos de ingreso, procesamiento y salida, que compensan la disminución algorítmica del espacio-tiempo, produciendo un reduccionismo vital en la sustentación de la vida humana en el planeta.  Esta situación, estudiada demográficamente, nos impulsa a lo que todos sabemos:  la necesidad de restringir <i>por sistema</i> los índices de natalidad y mejorar los de morbilidad, mortalidad, producción alimentaria y productividad.
	
<li>La única compensación posible es que el sistema global, con sus  microciclos, pueda controlar que los mismos deriven en mesociclos y macrociclos envolventes, éticos y progresivos, y que todos ellos, en orden sucesivo, abran sus ángulos de tal manera que la apertura conoidal del conjunto se inscriba en la saturación de una esfera de conocimiento. La humanidad entera necesita urgentemente más saberes sobre su propia realidad de cambio, sobre su geo-historia de la energía  y ello implica <i>supervivencia</i> para lograr la salida del hombre del planeta, puesto que los objetivos y metas concretas se vuelven cada vez más escasos, mientras el planeta densifica sus carencias en la gradiente integrada de una  ecología humana sin sustentación consolidada.
</ol>
	
<p>No podemos separar la velocidad,  ni del uso del espacio y el tiempo, ni de la aceleración ni de la realidad.

<p>A su vez, la <i>Velocidad</i> como función trascendente, es la derivada del espacio-tiempo y por lo tanto un estado de transferencia continua, característica esencial de toda realidad. O sea, de toda vibración, oscilación y de todo movimiento corpuscular, cuántico, atómico, molecular, orgánico, individual, social,   colectivo y social,  bien sea de tendencia a la política, a través de los espacios conceptuales y valorativos, o a la economía a través de los valores de intercambio político o económico. 

<p>También lo es a los ciclos etioteleológicos de causa a efecto, o sea la función <i>profundidad</i>, y a la intensificación de los movimientos tangenciales de las órbitas conoidales. Todas estas funciones trascendentes son correlativas, progresivas y acumulativas. Ellas denotan con toda  claridad su integración <i>real</i>. 

<p>La velocidad es y resume el estado de transferencia característica de toda la naturaleza, de la cultura y la sociedad en todas sus formas, que por tendencia natural en la reducción planetaria, se traducen en mayor complejidad y dificultad.

<p>Una crisis civilizatoria y una nueva formulación coherente de visión filosófica y epistemológica, sólo es posible cuando en forma angustiosa, pero afortunadamente coincidente, sobrevienen los cambios de época astrofísica y zodiacal, del segundo al tercer milenio; el cambio de edad, pasando desde las técnicas de industrialización y de computación elemental  a la tecnología electrónica y de las telecomunicaciones de orientación sideral, con su colateralidad de percepciones remotas; todo eso, sin perder el espacio y tiempo real,  y por último un cambio de <i>ERA</i> que va acompañado de mutaciones axiológicas, altamente peligrosas, por cuanto también los conceptos y los valores que éstos generan se degradan al entrar en  acción  las armas de la destrucción encadenada, sea de carácter moral e intangible, de carácter psicológico y axiológico o las armas de guerra para la  destrucción masiva del ser humano.

<p>Es altamente deseable que entre las mutaciones e intercambio de valores,  surja, además de los valores de la materialidad, la sexualidad y la gestoría hacia los vicios, la formulación que genere coherencia de filosofía política, redistribución de factores humanos y culturales de desarrollo, descentralización y desconcentración paulatina, y un poco más de alternabilidad intercambiable de sistemas de justicia humana y ecológica.

<p>Deseamos y luchamos porque la velocidad de la velocidad, o sea, la aceleración de los conceptos o constructos intencionales y las acciones respectivas, como ingredientes existenciales entre el espacio-tiempo y los flujos de energía-información, sean, al menos,  un nuevo paradigma teórico, como un camino coherente hacia un destino integrado y útil, además de oportuno, donde surja  un criterio de estrategia inteligente hacia la subsistencia, la convivencia y la supervivencia.

<p>Es justamente el sistema inteligente, a todo nivel, el que nos ocupa. Aquel que permite utilizar los flujos desagregados en cada jurisdicción y territorio a favor de una interpretación inteligente de compensación entre necesidades sentidas de la población en general y las capacidades que surgen de la dinamización y aceleración de las transferencias, dirigidas a la transformación en el aumento de la calidad de vida por sistema. Eso es el <i>Municipio Inteligente</i>. También podría ser una región, un estado, un continente o el planeta entero: un sistema de información e inteligencia de los servicios del desarrollo humano.

<p>Muchas capacidades se mantienen ocultas por la sencilla razón de que los sistemas de información de inteligencia no caminan a la misma velocidad  que la tecnología  en la producción  y el consumo masivo de bienes y servicios. Recordemos que la teoría económica interpreta un mundo equilibrado de oferta y demanda, o punto de equilibrio, que sin lugar a duda alguna, protege la economía del mercado, pero deja afuera la unidad conceptual y valorativa del concepto básico de subsistencia. Es sobre esta unidad y su presencia compleja  donde surge la indispensabilidad de una nueva civilización.

<p>Pero el concepto básico acelera la acción productiva e incrementa los índices de productividad, como variable compensatoria y proporcional a la propia economía del mercado. Lo difícil es convencer al propietario del  <i>poder posesivo</i> en la sociedad, que su parcial renuncia a  lo único que afecta es a la injusticia, convertida hoy en día en todo un sistema planetario de destrucción inminente.
	 
<p>Existe  también una aberración que es necesario denunciar con toda claridad. En estado natural, o sea, sin afectaciones artificiales de ingerencia humana, cuando se aceleran los sistemas comunicacionales surge un aumento en los sistemas de información; igualmente surge un aumento en la información de inteligencia y en la interpretación misma de la realidad. Cuando esos procesos son muy veloces y se tiene poca capacidad interpretativa de la realidad, es cuando entramos en una verdadera crisis. Esta vez no es por ausencia de información o por ignorancia, sino por excesiva confusión en su interpretación anárquica, cuya fuente es la ausencia de valores prioritarios.

<p>Cuando se instalan sistemas inteligentes en cualquier localidad, no existe dificultad alguna en activar las capacidades de la comunidad organizada y en que ésta comience a autogestionar gran parte de sus  necesidades sentidas. En todo caso, el propio sistema de información genera las vertientes y variables de una función supletoria de la acción del estado.

<p>La aberración consiste en que a los sistemas de tecnología, y por lo tanto de interpretación inteligente, no tienen acceso ni los gobiernos locales ni tampoco el cuerpo social, quienes se debaten entre una ignorancia cultural que afecta su conciencia de identidad y realidad y la escasez de medios propios; de la carencia total de tecnología, complementada con la situación de miseria, conjuntamente con la ignorancia correlativa.  El exceso de velocidad en los altos niveles de la sociedad y la carencia en los inferiores, establece una brecha de poder y posesión que, contrario a lo que se piensa, en el sentido de que las bases sociales son débiles, debe entenderse con toda claridad que lo endeble es todo el sistema.  <i>Un cuerpo macrocefálico es siempre tan endeble como lo sea su capacidad de soporte permanente</i>. Todo nuestro sistema está solamente esperando un impacto de cualquier naturaleza para explotar, porque ya está  amenazado intensamente del peor desequilibrio:   el conoide anti-civilizatorio. 

<p>Una analogía  debe mostrar siempre una finalidad en forma de apertura, que significa la incorporación con superávit gradual de trabajo (energía) y empleos útiles, producción, tecnología, sustentación vital, etc. y de inteligencia; también de interpretación gradual de la realidad.

<p>Otro obstáculo para el mejoramiento de la calidad de vida es la lentitud con la que se mueven los sistemas gubernamentales en todos los niveles. En efecto, las decisiones se han convertido hasta la exacerbación, en sistemas inorgánicos, burocratizados e ineficientes, que alargan la longitud de onda de los ajustes, mientras las necesidades  crecen,  se interactivan y se aceleran en proporciones que alteran toda esperanza de mejoramiento inteligente. Es imposible que  cuando se pierden las energías concurrentes al  propio destino de los pueblos,  cuando las estructuras político-administrativas consumen el fluido de los valores de intercambio en el gasto, y se desconocen los principios básicos de la inversión social, altamente reproductiva,  se pueda hacer un gobierno bueno y eficaz.

<p>A todos estos ajustes de un sistema que se degrada y degrada a la sociedad, se suma que  la información que fluye, la que debería ser insumo de inteligencia útil, completa y oportuna, resulta, en la mayor parte de las veces, inocua, incompleta y obsoleta, llegando, a veces, a ser simple  basura, pornográfica y delicuencial. 

<p>Por lo tanto, la función <i>velocidad</i>, que se integra con la poca <i>profundidad</i> de la gestión gubernativa y la escasa <i>intensidad</i> en el efecto del crecimiento orgánico de los sistemas co-existenciales del pueblo, del territorio y del gobierno,  mal  relacionados entre sí, no puede  ejecutarse adecuadamente. Lo cual sucede por dos razones prácticas: no existe la legislación adecuada. En Venezuela, por lo menos ya ha comenzado a aflorar un texto de Estado social descentralizado y que traslada competencias del poder público nacional a los estados, municipios y al cuerpo social . La otra razón es que la estructura político administrativa ha sido incoherente en el aspecto sectorial, en el aspecto orgánico jurisdiccional y en el aspecto de carencia de sistemas de información progresivos. 

<p>Las dos tesis que se integran cuando se esbozan la <i>Geotemática del Sistema Espacio</i> y la Tesis del <i>Municipio Inteligente</i>, conjuntamente planteados con una legislación adecuada, podrían muy bien establecer un principio de modelo concurrente y adecuado al logro y mantenimiento progresivo de la calidad de vida.

<p>Es lógico pensar que no será fácil transferir a las autoridades locales y a la clase  social de bajo nivel cultural  los argumentos de la Dimensión Cualitativa; tampoco será para elevados niveles académicos si están afianzados rígidamente en las perspectivas científicas  unisectoriales y de mucha profundidad dentro de un solo objeto. En cambio, serán fácilmente transferibles a aquellas personas cultas o que están involucradas en la trans o interdisciplinariedad. 

<p>Pero afortunadamente  la forma como se han efectuado estas investigaciones,  ha producido modelos de investigación extensiva de variadas, adecuadas,  concurrentes y complejas formas de vida. Este esquema dimensional fructifica intensamente con los regímenes jurídicos de interés social. En este momento se adapta la actual constitución de la República Bolivariana de Venezuela, con la Ley de los Consejos Locales de Planificación Pública, con la Ley de Geografía, Cartografía y Catastro, con la Ley de los Consejos Estadales de Planificación y Coordinación Pública y con otras cinco  conexiones de normas de la actual y vigente legislación venezolana.

<p>Por lo tanto, con la puesta en vigencia de estas leyes, se abre un camino adecuado a la incorporación de la autogestión y cogestión de la comunidad estructurada en funciones de participación protagónica de ciudadanos comunes y de comunidades organizadas.

<p>La aplicación de los sistemas de inteligencia está por encima, y como envolvente, de todo tipo de legislación, ya que es materia a largo plazo de ajustes y corrección de errores que se cometieron en los principios de su  filosofía política, que no podían ser detectados suficientemente para ser ajustados socialmente. El sistema  puede ser ventajosamente aplicado en cualquier orden, desde lo familiar hasta lo mundial, porque su estructura funcional se encuentra vinculada con formas universales y lógicas de proceder, a través de sistemas de comunicación, información, inteligencia y activación instalados sobre códigos de territorio; programas cronológicamente establecidos, y objetivos y metas alimentados, controlados y evaluados en forma continua por la vía del propio sistema.

<p>Es obvio que la velocidad del proceso depende de una buena capacitación del grupo direccionador y facilitador, que una vez organizados todos los sistemas, sólo tiene la labor de informatizar las transferencias para lograr la transformación total de la población y de su área respectiva    

<p>Los Sistemas de mejoramiento progresivo de la calidad de vida pasan necesaria, y existencialmente hablando,  por los sistemas de información social  debidamente inteligenciados hacia una activación cultural de producción y consumos proporcionales  al esfuerzo que hacen la sociedad y el gobierno, y a su concurrencia con el espacio vita,l con  una velocidad de diseño que nos permita subsistir, sobrevivir y, preferiblemente, estar en paz.

<p>Tanto el nuevo paradigma de un cambio eficiente y al mismo tiempo civilizatorio, que proviene de una forma de pensar y saber hacer el bien común, son indispensables y coincidentes con nuevas formas de pensamiento, conocimiento y acciones pertinentes y aceleradas hacia un nuevo equilibrio y redistribución de recursos relacionados con la realidad cambiante en sus cinco dimensiones, insertadas integralmente a los tres microsistemas de la realidad.

<div class=menu><table width=100% border=0><tr><td align=left width=33%><a href="intensidad.php">Función Intensidad</a></td>
	<td align=center width=33%><a href=index.html>Indice</a></td>
	<td align=right WIDTH=33%>&nbsp;</td></tr></table></div></body>

</html>
